
#include <stdio.h>
#include <stdint.h>
#include "../universalprogrammer_pinout.h"
#include "../eprom.h"

int main(void)
{
  int i;
  uint32_t temp;
  
  printf("// generated by makelut_27xx.c\r\n");
  printf("// (C)hris 2025\r\n\r\n");

  printf("const uint32_t lut_27xx_lo[] ={");

  for(i=0; i<256; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_27XX_A0;
    if(i&0x02) temp|=UP_27XX_A1;
    if(i&0x04) temp|=UP_27XX_A2;
    if(i&0x08) temp|=UP_27XX_A3;
    if(i&0x10) temp|=UP_27XX_A4;
    if(i&0x20) temp|=UP_27XX_A5;
    if(i&0x40) temp|=UP_27XX_A6;
    if(i&0x80) temp|=UP_27XX_A7;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  printf("const uint32_t lut_27xx_mi[] ={");

  for(i=0; i<256; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_27XX_A8;
    if(i&0x02) temp|=UP_27XX_A9;
    if(i&0x04) temp|=UP_27XX_A10;
    if(i&0x08) temp|=UP_27XX_A11;
    if(i&0x10) temp|=UP_27XX_A12;
    if(i&0x20) temp|=UP_27XX_A13;
    if(i&0x40) temp|=UP_27XX_A14;
    if(i&0x80) temp|=UP_27XX_A15;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  printf("const uint32_t lut_27xx_hi[] ={");

  for(i=0; i<16; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_27XX_A16;
    if(i&0x02) temp|=UP_27XX_A17;
    if(i&0x04) temp|=UP_27XX_A18;
    if(i&0x08) temp|=UP_27XX_A19;
    
    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  printf("const uint32_t lut_27xx_dat[] ={");
  
  for(i=0; i<256; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_27XX_D0;
    if(i&0x02) temp|=UP_27XX_D1;
    if(i&0x04) temp|=UP_27XX_D2;
    if(i&0x08) temp|=UP_27XX_D3;
    if(i&0x10) temp|=UP_27XX_D4;
    if(i&0x20) temp|=UP_27XX_D5;
    if(i&0x40) temp|=UP_27XX_D6;
    if(i&0x80) temp|=UP_27XX_D7;   
    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");

  return 0;
}
