services:
  dev:
    image: wyatt3arp/buspirate_v5plus
    build: ./docker
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - .:/project
      - /dev/bus/usb:/dev/bus/usb
    working_dir: '/project'
