services:
  dev:
    image: wyatt3arp/buspirate_v5
    build: ./docker
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    volumes:
      - .:/project
      - /dev/bus/usb:/dev/bus/usb
    working_dir: '/project'
