void script_print(const char *str);
void binmode_terminal_lock(bool lock);
uint32_t binmode_config(uint8_t *binmode_args);
uint32_t binmode_write(uint8_t *binmode_args);
uint32_t binmode_start(uint8_t *binmode_args);
uint32_t binmode_start_alt(uint8_t *binmode_args);
uint32_t binmode_stop(uint8_t *binmode_args);
uint32_t binmode_stop_alt(uint8_t *binmode_args);
uint32_t binmode_read(uint8_t *binmode_args);
uint32_t binmode_clkh(uint8_t *binmode_args);
uint32_t binmode_clkl(uint8_t *binmode_args);
uint32_t binmode_tick(uint8_t *binmode_args);
uint32_t binmode_dath(uint8_t *binmode_args);
uint32_t binmode_datl(uint8_t *binmode_args);
uint32_t binmode_bitr(uint8_t *binmode_args);
//global
uint32_t binmode_reset(uint8_t *binmode_args);
uint32_t binmode_debug_level(uint8_t *binmode_args);
uint32_t binmode_psu_enable(uint8_t *binmode_args);
uint32_t binmode_psu_disable(uint8_t *binmode_args);
uint32_t binmode_pullup_enable(uint8_t *binmode_args);
uint32_t binmode_pullup_disable(uint8_t *binmode_args);
uint32_t mode_list(uint8_t *binmode_args);
uint32_t mode_change(uint8_t *binmode_args);
uint32_t binmode_info(uint8_t *binmode_args);
uint32_t binmode_hwversion(uint8_t *binmode_args);
uint32_t binmode_fwversion(uint8_t *binmode_args);
uint32_t binmode_bitorder_msb(uint8_t *binmode_args);
uint32_t binmode_bitorder_lsb(uint8_t *binmode_args);
uint32_t binmode_aux_direction_mask(uint8_t *binmode_args);
uint32_t binmode_aux_read(uint8_t *binmode_args);
uint32_t binmode_aux_write_mask(uint8_t *binmode_args);
uint32_t binmode_adc_select(uint8_t *binmode_args);
uint32_t binmode_adc_read(uint8_t *binmode_args);
uint32_t binmode_adc_raw(uint8_t *binmode_args);
uint32_t binmode_pwm_enable(uint8_t *binmode_args);
uint32_t binmode_pwm_disable(uint8_t *binmode_args);
uint32_t binmode_pwm_raw(uint8_t *binmode_args);
uint32_t binmode_freq(uint8_t *binmode_args);
uint32_t binmode_freq_raw(uint8_t *binmode_args);
uint32_t binmode_delay_us(uint8_t *binmode_args);
uint32_t binmode_delay_ms(uint8_t *binmode_args);
uint32_t binmode_bootloader(uint8_t *binmode_args);
uint32_t binmode_reset_buspirate(uint8_t *binmode_args);
uint32_t binmode_change_binmode(uint8_t *binmode_args);

extern uint8_t binmode_debug;

#define BINMODE_MAX_ARGS 10