# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModeConfiguration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModeConfiguration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModeConfiguration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModeConfiguration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModeConfiguration
    def SpeedKhz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ModeConfigurationStart(builder):
    builder.StartObject(1)

def Start(builder):
    ModeConfigurationStart(builder)

def ModeConfigurationAddSpeedKhz(builder, speedKhz):
    builder.PrependUint32Slot(0, speedKhz, 0)

def AddSpeedKhz(builder, speedKhz):
    ModeConfigurationAddSpeedKhz(builder, speedKhz)

def ModeConfigurationEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModeConfigurationEnd(builder)
