# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

class RequestPacketContents(object):
    NONE = 0
    StatusRequest = 1
    ConfigurationRequest = 2
    DataRequest = 3
