# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestPacket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestPacket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestPacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestPacket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestPacket
    def VersionMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RequestPacket
    def VersionMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # RequestPacket
    def ContentsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RequestPacket
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RequestPacketStart(builder):
    builder.StartObject(4)

def Start(builder):
    RequestPacketStart(builder)

def RequestPacketAddVersionMajor(builder, versionMajor):
    builder.PrependUint8Slot(0, versionMajor, 0)

def AddVersionMajor(builder, versionMajor):
    RequestPacketAddVersionMajor(builder, versionMajor)

def RequestPacketAddVersionMinor(builder, versionMinor):
    builder.PrependUint8Slot(1, versionMinor, 1)

def AddVersionMinor(builder, versionMinor):
    RequestPacketAddVersionMinor(builder, versionMinor)

def RequestPacketAddContentsType(builder, contentsType):
    builder.PrependUint8Slot(2, contentsType, 0)

def AddContentsType(builder, contentsType):
    RequestPacketAddContentsType(builder, contentsType)

def RequestPacketAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    RequestPacketAddContents(builder, contents)

def RequestPacketEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestPacketEnd(builder)
