# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponsePacket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponsePacket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponsePacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResponsePacket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponsePacket
    def VersionMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ResponsePacket
    def VersionMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # ResponsePacket
    def ContentsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ResponsePacket
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ResponsePacketStart(builder):
    builder.StartObject(4)

def Start(builder):
    ResponsePacketStart(builder)

def ResponsePacketAddVersionMajor(builder, versionMajor):
    builder.PrependUint8Slot(0, versionMajor, 0)

def AddVersionMajor(builder, versionMajor):
    ResponsePacketAddVersionMajor(builder, versionMajor)

def ResponsePacketAddVersionMinor(builder, versionMinor):
    builder.PrependUint8Slot(1, versionMinor, 1)

def AddVersionMinor(builder, versionMinor):
    ResponsePacketAddVersionMinor(builder, versionMinor)

def ResponsePacketAddContentsType(builder, contentsType):
    builder.PrependUint8Slot(2, contentsType, 0)

def AddContentsType(builder, contentsType):
    ResponsePacketAddContentsType(builder, contentsType)

def ResponsePacketAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    ResponsePacketAddContents(builder, contents)

def ResponsePacketEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResponsePacketEnd(builder)
