# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

class ResponsePacketContents(object):
    NONE = 0
    ErrorResponse = 1
    StatusResponse = 2
    ConfigurationResponse = 3
    DataResponse = 4
