/*
 * This file is part of the Bus Pirate project (http://code.google.com/p/the-bus-pirate/).
 *
 * Written and maintained by the Bus Pirate project.
 *
 * To the extent possible under law, the project has
 * waived all copyright and related or neighboring rights to Bus Pirate. This
 * work is published from United States.
 *
 * For details see: http://creativecommons.org/publicdomain/zero/1.0/.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Binary access modes for Bus Pirate scripting */

// #include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pirate.h"
#include "queue.h"
#include "usb_rx.h"
#include "usb_tx.h"
#include "pirate.h"
// #include "sump.h"
#include "command_struct.h" //needed for same reason as bytecode and needs same fix
#include "bytecode.h"
#include "modes.h"
#include "binio_helpers.h"
#include "tusb.h"
#include "binmode/binio.h"
#include "system_config.h"
#include "pirate/amux.h"
#include "commands/global/w_psu.h"
#include "pirate/bio.h"
#include "commands/global/p_pullups.h"
#include "pirate/psu.h"
#include "commands/global/cmd_mcu.h"
#include "pirate/hwi2c_pio.h"
#include "mode/hwi2c.h"

enum binmode_statemachine {
    BINMODE_IDLE = 0,
    BINMODE_HEADER1,
    BINMODE_PACKET
};

const char dirtyproto_mode_name[] = "BPIO2 flatbuffer interface";

#include "bpio_builder.h" // Generated by `flatcc`.
#include "bpio_reader.h"  // Add this for bpio_bool_vec_len and related functions.

// A helper to simplify creating vectors from C-arrays.
#define c_vec_len(V) (sizeof(V)/sizeof((V)[0]))

// This allows us to verify result in optimized builds.
#define test_assert(x) do { if (!(x)) { assert(0); return -1; }} while(0)

bool bpio_debug = false;

static bool mode_change_new(const char *mode_name, bpio_mode_configuration_t *mode_config) {
    // compare mode name to modes.protocol_name
    for (uint8_t i = 0; i < count_of(modes); i++) {
        if (strcasecmp(mode_name, modes[i].protocol_name) == 0) {
            if(modes[i].bpio_handler==NULL) {
                if(bpio_debug) printf("[Mode Change] Protocol %s does not support BPIO handler\r\n", mode_name);
                return true;
            }
            modes[system_config.mode].protocol_cleanup();
            system_config.mode = i;
            if(modes[system_config.mode].bpio_configure==NULL) {
                if(bpio_debug) printf("[Mode Change] Protocol %s does not support BPIO configuration\r\n", mode_name);
            }else{
                modes[system_config.mode].bpio_configure(mode_config);
            }
            modes[system_config.mode].protocol_setup_exc();
            return false;
        }
    }
    return true;
}

static inline void send_packet(flatcc_builder_t *B) {
    uint8_t* buf;
    size_t len = flatcc_builder_get_buffer_size(B);
    if(bpio_debug) printf("[Send Packet] Length %d\r\n", len);
    buf = flatcc_builder_finalize_buffer(B, &len);
    if(bpio_debug) printf("[Send Packet] Finalized buffer\r\n");
    //send two byte length header
    uint8_t header[2];
    header[0] = len & 0xFF; // LSB
    header[1] = (len >> 8) & 0xFF; // MSB
    bin_tx_fifo_put(header[0]);
    bin_tx_fifo_put(header[1]);
    for(size_t i = 0; i < len; i++) {
        bin_tx_fifo_put(buf[i]);
    }
    free(buf); // Free the buffer allocated by flatcc_builder_finalize_buffer
    flatcc_builder_reset(B);
}

uint32_t status_request(bpio_RequestPacket_table_t packet, flatcc_builder_t *B) {
    bpio_StatusRequest_table_t status_request = (bpio_StatusRequest_table_t) bpio_RequestPacket_contents(packet);
    test_assert(status_request != 0);

    bpio_StatusRequestTypes_vec_t query = bpio_StatusRequest_query(status_request);

    uint32_t query_flags=0;
    // Make sure the vector is accessible.
    if(query == 0){ //no query, send all
        query_flags|= 1u<<bpio_StatusRequestTypes_All;
    }else{
        // Iterate through the vector
        if(bpio_debug) printf("[Status Request] Query types: ");
        for (size_t i = 0; i < bpio_StatusRequestTypes_vec_len(query); i++) {
            bpio_StatusRequestTypes_enum_t query_type = bpio_StatusRequestTypes_vec_at(query, i);
            if(bpio_debug) printf("%zu ", query_type);
            // Set the corresponding bit in query_flags
            query_flags |= (1u << query_type);
        }
        if(bpio_debug) printf("\r\n");
    }

    flatcc_builder_reset(B);

    bpio_StatusResponse_start(B);
    if(query_flags & (1u << bpio_StatusRequestTypes_Version)||query_flags & (1u << bpio_StatusRequestTypes_All)) {
        // Send version information
        if(bpio_debug) printf("[Status Request] Version requested\r\n");
        bpio_StatusResponse_hardware_version_major_add(B, BP_FIRMWARE_VERSION_MAJOR);
        bpio_StatusResponse_hardware_version_minor_add(B, BP_FIRMWARE_VERSION_REVISION);
        bpio_StatusResponse_firmware_version_major_add(B, 0);
        bpio_StatusResponse_firmware_version_minor_add(B, 0);
        flatbuffers_string_ref_t git_hash = flatbuffers_string_create_str(B, BP_FIRMWARE_HASH);
        bpio_StatusResponse_firmware_git_hash_add(B, git_hash);
        flatbuffers_string_ref_t firmware_date = flatbuffers_string_create_str(B, BP_FIRMWARE_TIMESTAMP);
        bpio_StatusResponse_firmware_date_add(B, firmware_date);

    }

    //modes_available and current mode
    if(query_flags & (1u << bpio_StatusRequestTypes_Mode) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] Modes available requested\r\n");
        
        flatbuffers_string_ref_t current_mode_name = flatbuffers_string_create_str(B, modes[system_config.mode].protocol_name);
        bpio_StatusResponse_mode_current_add(B, current_mode_name);

        bpio_StatusResponse_modes_available_start(B); // <-- Start the vector!
        for (uint8_t i = 0; i < count_of(modes); i++) {
            flatbuffers_string_ref_t name = flatbuffers_string_create_str(B, modes[i].protocol_name);
            bpio_StatusResponse_modes_available_push(B, name);
        }        
        bpio_StatusResponse_modes_available_end(B); // <-- End the vector!

        bpio_StatusResponse_mode_pin_labels_start(B);
        for (uint8_t i = 0; i < HW_PINS; i++) {
            flatbuffers_string_ref_t label = flatbuffers_string_create_str(B, system_config.pin_labels[i]);
            bpio_StatusResponse_mode_pin_labels_push(B, label);
        }
        bpio_StatusResponse_mode_pin_labels_end(B);

        bpio_StatusResponse_mode_bitorder_msb_add(B, system_config.bit_order == 0);
    }

    // led_count
    if(query_flags & (1u << bpio_StatusRequestTypes_LED) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] LED count requested\r\n");
        bpio_StatusResponse_led_count_add(B, RGB_LEN);
    }

    // Pullup status
    if(query_flags & (1u << bpio_StatusRequestTypes_Pullup) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] Pullup status requested\r\n");
        bpio_StatusResponse_pullup_enabled_add(B, system_config.pullup_enabled);
        #ifdef BP_HW_PULLX
        bpio_StatusResponse_pullx_config_add(B, 0x00000000u); //todo: implement pull-x config
        #endif
    }

    // PSU status
    if(query_flags & (1u << bpio_StatusRequestTypes_PSU) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] PSU status requested\r\n");
        bpio_StatusResponse_psu_enabled_add(B, system_config.psu);
        bpio_StatusResponse_psu_set_mv_add(B, system_config.psu_voltage/10);
        bpio_StatusResponse_psu_set_ma_add(B, system_config.psu_current_limit/10000);
        uint32_t vout, isense, vreg;
        bool fuse;
        psu_measure(&vout, &isense, &vreg, &fuse);
        bpio_StatusResponse_psu_measured_mv_add(B, vout);
        bpio_StatusResponse_psu_measured_ma_add(B, isense/1000);
        bpio_StatusResponse_psu_current_error_add(B, system_config.psu_current_error);

    }

    //ADC status, return the voltage on IO0...IO7
    if(query_flags & (1u << bpio_StatusRequestTypes_ADC) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] ADC status requested\r\n");
        amux_sweep();
        bpio_StatusResponse_adc_mv_start(B);
        for (uint8_t i = 1; i < 9; i++) {
            bpio_StatusResponse_adc_mv_push(B, hw_pin_voltage_ordered[i]);
        }
        bpio_StatusResponse_adc_mv_end(B);
    }

    // IO status
    if(query_flags & (1u << bpio_StatusRequestTypes_IO) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] IO status requested\r\n");
        // direction is 0-7
        // value is 8-15
        uint32_t pins = gpio_get_all();
        bpio_StatusResponse_io_direction_add(B, (uint8_t)(pins & 0xff)); // Get the first 8 bits for direction
        bpio_StatusResponse_io_value_add(B, (uint8_t)((pins >> 8) & 0xff)); // Get the next 8 bits for value        
    }

    // Disk status
    if(query_flags & (1u << bpio_StatusRequestTypes_Disk) || query_flags & (1u << bpio_StatusRequestTypes_All)) {
        if(bpio_debug) printf("[Status Request] Disk status requested\r\n");
        bpio_StatusResponse_disk_size_mb_add(B, system_config.storage_size * 1000);
        bpio_StatusResponse_disk_used_mb_add(B, 0.0f); //todo: implement disk free space    
    }

    // end status response table
    bpio_StatusResponse_ref_t status_response = bpio_StatusResponse_end(B);
    
    // add to packet wrapper
    bpio_ResponsePacket_start_as_root(B);
    bpio_ResponsePacket_contents_StatusResponse_add(B, status_response);
    bpio_ResponsePacket_end_as_root(B);            
    // send the packet
    send_packet(B);
}


uint32_t configuration_request(bpio_RequestPacket_table_t packet, flatcc_builder_t *B) {
    bpio_ConfigurationRequest_table_t config_request = (bpio_ConfigurationRequest_table_t) bpio_RequestPacket_contents(packet);
    test_assert(config_request != 0);

    const char *error = NULL;

    // does it have mode?
    if(bpio_ConfigurationRequest_mode_is_present(config_request)) {
        // change mode
        const char* mode_str = bpio_ConfigurationRequest_mode_get(config_request);
        //get the mode configuration
        bpio_ModeConfiguration_table_t mode_config = bpio_ConfigurationRequest_mode_configuration(config_request);
        if(mode_config == 0){
            static const char *mode_config_error_msg = "Mode configuration not present";
            if(bpio_debug) printf("[Config Request] Error: %s\r\n", mode_config_error_msg);
            error = mode_config_error_msg;
            goto config_response_error;
        }
        bpio_mode_configuration_t mode_config_data;
        mode_config_data.speed = bpio_ModeConfiguration_speed_get(mode_config);
        mode_config_data.data_bits = bpio_ModeConfiguration_data_bits_get(mode_config);
        mode_config_data.parity = bpio_ModeConfiguration_parity_get(mode_config);
        mode_config_data.stop_bits = bpio_ModeConfiguration_stop_bits_get(mode_config);
        mode_config_data.flow_control = bpio_ModeConfiguration_flow_control_get(mode_config);
        mode_config_data.signal_inversion = bpio_ModeConfiguration_signal_inversion_get(mode_config);
        mode_config_data.clock_stretch = bpio_ModeConfiguration_clock_stretch_get(mode_config);
        mode_config_data.clock_polarity = bpio_ModeConfiguration_clock_polarity_get(mode_config);
        mode_config_data.clock_phase = bpio_ModeConfiguration_clock_phase_get(mode_config);
        mode_config_data.chip_select_active_low = bpio_ModeConfiguration_chip_select_active_low_get(mode_config);
        mode_config_data.submode = bpio_ModeConfiguration_submode_get(mode_config);
        mode_config_data.tx_modulation = bpio_ModeConfiguration_tx_modulation_get(mode_config);
        mode_config_data.rx_sensor = bpio_ModeConfiguration_rx_sensor_get(mode_config);
        mode_config_data.debug = bpio_debug;
        
        if (mode_change_new(mode_str, &mode_config_data)) {
            static const char *mode_error_msg = "Invalid mode name";
            if(bpio_debug) printf("[Config Request] Error: %s '%s'\r\n", mode_error_msg, mode_str);
            error = mode_error_msg;
            goto config_response_error;
        }
        //todo: configure mode
        if(bpio_debug) printf("[Config Request] Mode changed to '%s'\r\n", mode_str);
    }

    //bit orders
    bool bit_order_msb = bpio_ConfigurationRequest_mode_bitorder_msb_get(config_request);
    if(bit_order_msb) {
        system_config.bit_order = 0; // MSB first
        if(bpio_debug) printf("[Config Request] Bit order set to MSB first\r\n");
    }

    bool bit_order_lsb = bpio_ConfigurationRequest_mode_bitorder_lsb_get(config_request);
    if(bit_order_lsb) {
        system_config.bit_order = 1; // LSB first
        if(bpio_debug) printf("[Config Request] Bit order set to LSB first\r\n");
    }

    bool psu_disable = bpio_ConfigurationRequest_psu_disable_get(config_request);
    if(psu_disable){
        psucmd_disable();
        if(bpio_debug) printf("[Config Request] Power supply disabled\r\n");
    }

    //psu_enabled
    bool psu_enable = bpio_ConfigurationRequest_psu_enable_get(config_request);
    if(psu_enable){
        uint32_t voltage_mv = 3300;
        if(bpio_ConfigurationRequest_psu_set_mv_is_present(config_request)) {
            voltage_mv = bpio_ConfigurationRequest_psu_set_mv_get(config_request);
            //check out of range
            if(voltage_mv < 800 || voltage_mv > 5000) {
                static const char *voltage_error_msg = "PSU Voltage out of range (800-5000 mV)";
                if(bpio_debug) printf("[Config Request] Error: %s (%d mV)\r\n", voltage_error_msg, voltage_mv);
                error = voltage_error_msg;
                goto config_response_error;
            }
        }
            
        uint32_t current_ma = 300; // default
        bool current_limit_override = false;
        if(bpio_ConfigurationRequest_psu_set_ma_is_present(config_request)) {
            current_ma = bpio_ConfigurationRequest_psu_set_ma_get(config_request);
            if(current_ma==0) {
                current_limit_override = true; // 0 means no limit
                if(bpio_debug) printf("[Config Request] PSU current limit override enabled\r\n");
            }else{
                //check out of range
                if(current_ma < 1 || current_ma > 500) {
                    static const char *current_error_msg = "PSU Current out of range (1-500 mA)";
                    if(bpio_debug) printf("[Config Request] Error: %s (%d mA)\r\n", current_error_msg, current_ma);
                    error = current_error_msg;
                    goto config_response_error;
                }
            }
        }

        if(bpio_debug) printf("[Config Request] PSU Voltage: %f, Current: %f, Override: %s\r\n", (float)voltage_mv/1000.0f, (float)current_ma, current_limit_override?"true":"false");
        
        uint8_t psu_error = psucmd_enable((float)voltage_mv/1000.0f, (float)current_ma, current_limit_override);
        if (psu_error) {
            static const char *psu_error_msg = "Power supply initialization failed";
            if(bpio_debug) printf("[Config Request] Error: %s (%d)\r\n", psu_error_msg, psu_error);
            error = psu_error_msg;
            goto config_response_error;
        }

        if(bpio_debug) printf("[Config Request] Power supply enabled\r\n");
    }

    uint8_t pullup_disable = bpio_ConfigurationRequest_pullup_disable_get(config_request);
    if(pullup_disable){
        pullups_disable();
        if(bpio_debug) printf("[Config Request] Pull-up resistors disabled\r\n");
    }

    //pullup_enabled
    //if(bpio_ConfigurationRequest_pullup_enabled_is_present(config_request)) {
        uint8_t pullup_enable = bpio_ConfigurationRequest_pullup_enable_get(config_request);
        if(pullup_enable){
            pullups_enable();
            if(bpio_debug) printf("[Config Request] Pull-up resistors enabled\r\n");
        }
    //}    
    
    #ifdef BP_HW_PULLX
    //pullx_config
    #endif

    //io_direction
    //TODO: this needs to respect any in-use pins (check system_config?)
    if(bpio_ConfigurationRequest_io_direction_mask_is_present(config_request)){
        uint8_t io_direction_mask = bpio_ConfigurationRequest_io_direction_mask_get(config_request);
        uint8_t io_direction = bpio_ConfigurationRequest_io_direction_get(config_request);
        for(uint8_t i = 0; i < 8; i++) {
            if(io_direction_mask & (1u << i)) {
                //set the direction
                if(io_direction & (1u << i)) {
                    // first set the buffer to output
                    gpio_put(i, BUFDIR_OUTPUT);
                    // now set pin to output
                    gpio_set_dir(i+8, GPIO_OUT);
                    if(bpio_debug) printf("[Config Request] IO%d set to output\r\n", i);
                }else{
                    // first set the pin to input
                    gpio_set_dir(i+8, GPIO_IN);
                    // now set buffer to input
                    gpio_put(i, BUFDIR_INPUT);
                    if(bpio_debug) printf("[Config Request] IO%d set to input\r\n", i);
                }
            }
        }
    }

    //io_value
    if(bpio_ConfigurationRequest_io_value_mask_is_present(config_request)) {
        uint8_t io_value_mask = bpio_ConfigurationRequest_io_value_mask_get(config_request);
        uint8_t io_value = bpio_ConfigurationRequest_io_value_get(config_request);
        for(uint8_t i = 0; i < 8; i++) {
            if(io_value_mask & (1u << i)) {
                //set the value
                gpio_put(i+8, (io_value & (1u << i)));
                if(bpio_debug) printf("[Config Request] IO%d set to %s\r\n", i, (io_value & (1u << i)) ? "high" : "low");
            }
        }    
    }

    //led_resume
    if(bpio_ConfigurationRequest_led_resume_is_present(config_request)) {
        bool led_resume = bpio_ConfigurationRequest_led_resume_get(config_request);
        if (led_resume) {
            if(bpio_debug) printf("[Config Request] LED effect resumed\r\n");
            rgb_irq_enable(true); // Enable the RGB IRQ
        }/* else {
            if(bpio_debug) printf("[Config Request] LED effect paused\r\n");
            rgb_irq_enable(false); // Disable the RGB IRQ
        }*/
    }

    //led_color
    if(bpio_ConfigurationRequest_led_color_is_present(config_request)) {
        flatbuffers_uint32_vec_t led_color = bpio_ConfigurationRequest_led_color_get(config_request);
        if(flatbuffers_uint32_vec_len(led_color) < RGB_LEN) {
            static const char *led_error_msg = "LED color vector (array) too short";
            if(bpio_debug) printf("[Config Request] Error: %s: %d, this device has %d LEDs\r\n", led_error_msg, flatbuffers_uint32_vec_len(led_color), RGB_LEN);
            error = led_error_msg;
            goto config_response_error;
        }else{
            uint32_t colors[RGB_LEN];
            if(bpio_debug) printf("[Config Request] LED colors: ");
            for (size_t i = 0; i < RGB_LEN; i++) {
                colors[i] = flatbuffers_uint32_vec_at(led_color, i);
                if(bpio_debug) printf("0x%06X ", colors[i]);
            }
            if(bpio_debug) printf("\r\n");
            rgb_irq_enable(false);
            rgb_set_array(colors);            
        }
    }

    //printf
    if(bpio_ConfigurationRequest_print_string_is_present(config_request)) {
        const char *print_str = bpio_ConfigurationRequest_print_string_get(config_request);
        if(bpio_debug) printf("%s", print_str);
    }

    //hardware_bootloader
    bool hardware_bootloader = bpio_ConfigurationRequest_hardware_bootloader_get(config_request);
    if(hardware_bootloader) {
        if(bpio_debug) printf("[Config Request] Entering bootloader mode\r\n");
        cmd_mcu_jump_to_bootloader();
    }

    //hardware_reset
    bool hardware_reset = bpio_ConfigurationRequest_hardware_reset_get(config_request);
    if(hardware_reset) {
        if(bpio_debug) printf("[Config Request] Hardware reset requested\r\n");
        cmd_mcu_reset();
    }

    flatcc_builder_reset(B);

config_response_error:
    bpio_ConfigurationResponse_start(B);
    // If there was an error, we can set it here.
    if (error) {
        // Set the error message in the response.
        flatbuffers_string_ref_t error_str = flatbuffers_string_create_str(B, error);
        bpio_ConfigurationResponse_error_add(B, error_str);
        if(bpio_debug) printf("%s\r\n", error);
    }
    bpio_ConfigurationResponse_ref_t config_response = bpio_ConfigurationResponse_end(B);
    
    // add to packet wrapper
    bpio_ResponsePacket_start_as_root(B);
    bpio_ResponsePacket_contents_ConfigurationResponse_add(B, config_response);
    bpio_ResponsePacket_end_as_root(B);            
    // send the packet
    send_packet(B);
}


uint32_t data_request(bpio_RequestPacket_table_t packet, flatcc_builder_t *B) {
    bpio_DataRequest_table_t data_request = (bpio_DataRequest_table_t) bpio_RequestPacket_contents(packet);
    test_assert(data_request != 0);

    const char *error = NULL;

    char data_buf[512]; // Buffer for data, adjust size as needed

    //check if each field is present, get value
    bool start_main = bpio_DataRequest_start_main(data_request);
    if(bpio_debug) printf("[Data Request] Start main condition: %s\r\n", start_main ? "true" : "false");

    // Check if start_alt is present and get its value.
    bool start_alt = bpio_DataRequest_start_alt(data_request);
    if(bpio_debug) printf("[Data Request] Start alternate condition: %s\r\n", start_alt ? "true" : "false");
   
    // Check if data_write is present and get its value.
    flatbuffers_uint8_vec_t data_write;
    uint16_t data_write_len = 0;
    if(bpio_DataRequest_data_write_is_present(data_request)) {
        data_write = bpio_DataRequest_data_write(data_request);
        data_write_len = flatbuffers_uint8_vec_len(data_write);
        if(bpio_debug) printf("[Data Request] Data write vector is present\r\n");
    }else{
        if(bpio_debug) printf("[Data Request] Data write vector is missing\r\n");
    }
    if (data_write_len > 0) {
        if(bpio_debug) printf("[Data Request] Data write vector length: %d\r\n", data_write_len);
        // Print the data write vector contents.
        if(bpio_debug) printf("[Data Request] Data write: ");
        for (size_t i = 0; i < data_write_len; i++) {
            if(bpio_debug) printf("0x%02X ", flatbuffers_uint8_vec_at(data_write, i));
            data_buf[i] = flatbuffers_uint8_vec_at(data_write, i); // Copy to data_buf
        }
        if(bpio_debug) printf("\r\n");
    }

    // Check if bytes_read is present and get its value.
    uint16_t readbytes = bpio_DataRequest_bytes_read(data_request);
    if(bpio_debug) printf("[Data Request] Bytes to read: %d\r\n", readbytes);

    // Check if stop_main is present and get its value.
    bool stop_main = bpio_DataRequest_stop_main(data_request);
    if(bpio_debug) printf("[Data Request] Stop main condition: %s\r\n", stop_main ? "true" : "false");

    // Check if stop_alt is present and get its value.
    bool stop_alt = bpio_DataRequest_stop_alt(data_request);
    if(bpio_debug) printf("[Data Request] Stop alternate condition: %s\r\n", stop_alt ? "true" : "false");

    // Now we can process the request.
    struct bpio_data_request_t request = {
        .debug = bpio_debug,
        .start_main = bpio_DataRequest_start_main(data_request),
        .start_alt = bpio_DataRequest_start_alt(data_request),
        .bytes_write = data_write_len, // Use the length of the data write vector
        .bytes_read = bpio_DataRequest_bytes_read(data_request),
        .data_buf = data_buf, // Initialize with the buffer
        .stop_main = bpio_DataRequest_stop_main(data_request),
        .stop_alt = bpio_DataRequest_stop_alt(data_request)
    };

    if(bpio_debug) printf("[Data Request] Protocol request\r\n");
    if(modes[system_config.mode].bpio_handler(&request)){
        static const char* request_error_msg = "Protocol request failed";
        if(bpio_debug) printf("[Data Request] %s\r\n", request_error_msg);
        error = request_error_msg;
    }

    flatcc_builder_reset(B);

    //prepare DataResponse, put mock up data in data_read if readbytes > 0
    bpio_DataResponse_start(B);
    if (readbytes > 0 && !error) {
        if(bpio_debug) printf("[Data Request] Returning read %d bytes\r\n", readbytes);
        // Create a vector for the data read.
        bpio_DataResponse_data_read_start(B);
        for (uint16_t i = 0; i < readbytes; i++) {
            bpio_DataResponse_data_read_push(B, &request.data_buf[i]); // Mock data, replace with actual read data.
        }
        bpio_DataResponse_data_read_end(B);
    }

    if(bpio_debug) printf("[Data Request] Data read added ");

data_response_error:
    if (error) {
        // Set the error message in the response.
        flatbuffers_string_ref_t error_str = flatbuffers_string_create_str(B, error);
        bpio_DataResponse_error_add(B, error_str);
        if(bpio_debug) printf("[Data Request] Error: %s\r\n", error);
    }

    if(bpio_debug) printf("[Data Request] Packing response\r\n");
    bpio_DataResponse_ref_t data_response = bpio_DataResponse_end(B);
    // add to packet wrapper
    bpio_ResponsePacket_start_as_root(B);
    bpio_ResponsePacket_contents_DataResponse_add(B, data_response);
    bpio_ResponsePacket_end_as_root(B);

    if(bpio_debug) printf("[Data Request] Response packet created\r\n");
       
    // send the packet
    send_packet(B);

    if(bpio_debug) printf("[Data Request] Packet sent\r\n");
}

struct _bpio_function_t {
    uint32_t (*func)(bpio_RequestPacket_table_t packet, flatcc_builder_t *B);
};

const static struct _bpio_function_t bpio_handlers[]={
    [bpio_RequestPacketContents_NONE] = { .func = NULL }, // No handler for unknown packets
    [bpio_RequestPacketContents_StatusRequest] = { .func = status_request },
    [bpio_RequestPacketContents_ConfigurationRequest] = { .func = configuration_request },
    [bpio_RequestPacketContents_DataRequest] = { .func = data_request },
};

void error_response(const char *error_msg) {
    // build response    
    flatcc_builder_t builder, *B;
    B = &builder;
    flatcc_builder_init(B);

    // Create a response packet with an error message.
    flatbuffers_string_ref_t error_str = flatbuffers_string_create_str(B, error_msg);
    
    bpio_ResponsePacket_contents_ErrorResponse_start(B);
    bpio_ErrorResponse_error_add(B, error_str);
    bpio_ErrorResponse_end(B);
    
    bpio_ResponsePacket_start_as_root(B);
    bpio_ResponsePacket_contents_ErrorResponse_add(B, bpio_ErrorResponse_end(B));
    bpio_ResponsePacket_end_as_root(B);
    
    // Send the packet.
    send_packet(B);

    flatcc_builder_clear(B);  
}

// handler needs to be cooperative multitasking until mode is enabled
void dirtyproto_mode(void) {
    binmode_debug = true;
    static uint8_t binmode_state = BINMODE_IDLE;

    uint8_t buf[500];
    static uint32_t len=0;
    char c; 
    
    if (!bin_rx_fifo_try_get(&c)) return;

    switch (binmode_state) {
        case BINMODE_IDLE:
            len=c;
            binmode_state = BINMODE_HEADER1;
            break;
        case BINMODE_HEADER1:
            len |= c << 8;
            bpio_debug = (system_config.bpio_debug_enable && tud_cdc_n_connected(0));
            if(len==0 || len>sizeof(buf)){ //TODO: on all fails return error response
                if(bpio_debug) printf("[BPIO] Flatbuffer size error: %d\r\n", len);
                // Send an error response.
                error_response("Flatbuffer size error: Invalid length");
                binmode_state = BINMODE_IDLE;
                break;
            }
            if(bpio_debug) printf("[BPIO] Flatbuffer length: %d\r\n", len);         
            binmode_state = BINMODE_PACKET;
            //break;
        case BINMODE_PACKET:
            //get len bytes
            for(uint32_t i=0; i<len; i++) {
                bin_rx_fifo_get_blocking(&c);
                buf[i] = c; // Store in reverse order
            }
            if(bpio_debug) printf("[BPIO] Flatbuffer received, length: %d\r\n", len);
            bpio_RequestPacket_table_t packet = bpio_RequestPacket_as_root(buf);
            if(packet == 0) {
                if(bpio_debug) printf("[BPIO] Error: Invalid table received\r\n");
                // Send an error response.
                error_response("Invalid table received");
                binmode_state = BINMODE_IDLE; // Reset state on error
                return;
            }
            uint8_t packet_type = bpio_RequestPacket_contents_type_get(packet);
            if(bpio_debug) printf("[BPIO] Packet Type: %d\r\n", packet_type);
            if (packet_type < count_of(bpio_handlers) && bpio_handlers[packet_type].func) {
                // build response    
                flatcc_builder_t builder, *B;
                B = &builder;
                flatcc_builder_init(B);
                // Call the handler function for this packet type.
                bpio_handlers[packet_type].func(packet, B);
                //flatcc_builder_reset(B);
                // build next buffer.
                // ...
                // Cleanup.
                flatcc_builder_clear(B);    
            } else {
                if(bpio_debug) printf("[BPIO] Unknown packet type: %d\r\n", packet_type);
                // Send an error response.
                error_response("Unknown packet type received");
            }
            binmode_state = BINMODE_IDLE; // Reset state after processing the packet
            break;
        default:
            if(bpio_debug) printf("[BPIO] Unknown binmode state: %d\r\n", binmode_state);
            binmode_state = BINMODE_IDLE;
            break;
    }

}
