
#include <stdio.h>
#include <stdint.h>
#include "../universalprogrammer_pinout.h"

int main(void)
{
  int i;
  uint32_t temp;
  
  printf("// generated by makelut_dl1414.c\r\n");
  printf("// (C)hris 2025-26\r\n\r\n");

  printf("const uint32_t lut_dl1414[] ={");

  for(i=0; i<128; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x001) temp|=UP_DL1414_D0;
    if(i&0x002) temp|=UP_DL1414_D1;
    if(i&0x004) temp|=UP_DL1414_D2;
    if(i&0x008) temp|=UP_DL1414_D3;
    if(i&0x010) temp|=UP_DL1414_D4;
    if(i&0x020) temp|=UP_DL1414_D5;
    if(i&0x040) temp|=UP_DL1414_D6;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  

  return 0;
}
