
#include <stdio.h>
#include <stdint.h>
#include "../universalprogrammer_pinout.h"

int main(void)
{
  int i;
  uint32_t temp;
  
  printf("// generated by makelut_dram41xx.c\r\n");
  printf("// (C)hris 2025\r\n\r\n");

  printf("const uint32_t lut_dram41xx[] ={");

  for(i=0; i<512; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x001) temp|=UP_DRAM41_A0;
    if(i&0x002) temp|=UP_DRAM41_A1;
    if(i&0x004) temp|=UP_DRAM41_A2;
    if(i&0x008) temp|=UP_DRAM41_A3;
    if(i&0x010) temp|=UP_DRAM41_A4;
    if(i&0x020) temp|=UP_DRAM41_A5;
    if(i&0x040) temp|=UP_DRAM41_A6;
    if(i&0x080) temp|=UP_DRAM41_A7;
    if(i&0x100) temp|=UP_DRAM41_A8;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  

  return 0;
}
