

import xml.etree.ElementTree as ET
import re

tree = ET.parse('logicic.xml')
root = tree.getroot()

pin14="static const char logictest14 [][15] = {\r\n" 
pin14cnt=0
pin14lut="static const up_logic logicic14[] = {\r\n"

pin16="static const char logictest16 [][17] = {\r\n"
pin16cnt=0
pin16lut="static const up_logic logicic16[] = {\r\n"

pin20="static const char logictest20 [][21] = {\r\n"
pin20cnt=0
pin20lut="static const up_logic logicic20[] = {\r\n"

pin24="static const char logictest24 [][25] = {\r\n"
pin24cnt=0
pin24lut="static const up_logic logicic24[] = {\r\n"

pin28="static const char logictest28 [][29] = {\r\n"
pin28cnt=0
pin28lut="static const up_logic logicic28[] = {\r\n"

pin40="static const char logictest40 [][41] = {\r\n"
pin40cnt=0
pin40lut="static const up_logic logicic40[] = {\r\n"

numics=0

for child in root:
    for child2 in child:
        for child3 in child2:
            attribs=child3.attrib
            

            if(attribs['pins']=="14"):
                pin14cntstart=pin14cnt;

                for child4 in child3:
                    pin14+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin14cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin14lut+="  { \""+ic+"\", "+str(pin14cntstart)+", "+str(pin14cnt)+" },\r\n"                
                    numics+=1;

            if(attribs['pins']=="16"):
                pin16cntstart=pin16cnt;

                for child4 in child3:
                    pin16+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin16cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin16lut+="  { \""+ic+"\", "+str(pin16cntstart)+", "+str(pin16cnt)+" },\r\n"                
                    numics+=1;
        
            if(attribs['pins']=="20"):
                pin20cntstart=pin20cnt;

                for child4 in child3:
                    pin20+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin20cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin20lut+="  { \""+ic+"\", "+str(pin20cntstart)+", "+str(pin20cnt)+" },\r\n"                
                    numics+=1;
        
            if(attribs['pins']=="24"):
                pin24cntstart=pin24cnt;

                for child4 in child3:
                    pin24+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin24cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin24lut+="  { \""+ic+"\", "+str(pin24cntstart)+", "+str(pin24cnt)+" },\r\n"                
                    numics+=1;
        
            if(attribs['pins']=="28"):
                pin28cntstart=pin28cnt;

                for child4 in child3:
                    pin28+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin28cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin28lut+="  { \""+ic+"\", "+str(pin28cntstart)+", "+str(pin28cnt)+" },\r\n"                
                    numics+=1;
        
            if(attribs['pins']=="40"):
                pin40cntstart=pin40cnt;

                for child4 in child3:
                    pin40+="  \""+re.sub("\\s", "", child4.text)+"\",  // "+attribs['name']+"\r\n"
                    pin40cnt+=1
                
                ics=re.split(",",attribs['name'])
                
                for ic in ics:
                    pin40lut+="  { \""+ic+"\", "+str(pin40cntstart)+", "+str(pin40cnt)+" },\r\n"                
                    numics+=1;
        
pin14lut+="};\r\n\r\n"
pin14+="};\r\n\r\n"
pin16lut+="};\r\n\r\n"
pin16+="};\r\n\r\n"
pin20lut+="};\r\n\r\n"
pin20+="};\r\n\r\n"
pin24lut+="};\r\n\r\n"
pin24+="};\r\n\r\n"
pin28lut+="};\r\n\r\n"
pin28+="};\r\n\r\n"
pin40lut+="};\r\n\r\n"
pin40+="};\r\n\r\n"


print("// generated by parse_logic.py")
print("// (C)hris 2025")
print("// uses .xml from https://gitlab.com/DavidGriffith/minipro")
print("// which borrowed it from https://github.com/Johnlon/integrated-circuit-tester")
print("// and https://github.com/akshaybaweja/Smart-IC-Tester")
print()
print("typedef struct up_logic {")
print("  char    name[16];")
print("  uint16_t start, end;")
print("} up_logic;")
print()


print(pin14lut)
print(pin14)
print(pin16lut)
print(pin16)
print(pin20lut)
print(pin20)
print(pin24lut)
print(pin24)
print(pin28lut)
print(pin28)
print(pin40lut)
print(pin40)

print("// number of ics: "+str(numics))
