#ifndef BPIO_READER_H
#define BPIO_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct bpio_StatusRequest_table *bpio_StatusRequest_table_t;
typedef struct bpio_StatusRequest_table *bpio_StatusRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_StatusRequest_vec_t;
typedef flatbuffers_uoffset_t *bpio_StatusRequest_mutable_vec_t;
typedef const struct bpio_StatusResponse_table *bpio_StatusResponse_table_t;
typedef struct bpio_StatusResponse_table *bpio_StatusResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_StatusResponse_vec_t;
typedef flatbuffers_uoffset_t *bpio_StatusResponse_mutable_vec_t;
typedef const struct bpio_ModeConfiguration_table *bpio_ModeConfiguration_table_t;
typedef struct bpio_ModeConfiguration_table *bpio_ModeConfiguration_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_ModeConfiguration_vec_t;
typedef flatbuffers_uoffset_t *bpio_ModeConfiguration_mutable_vec_t;
typedef const struct bpio_ConfigurationRequest_table *bpio_ConfigurationRequest_table_t;
typedef struct bpio_ConfigurationRequest_table *bpio_ConfigurationRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_ConfigurationRequest_vec_t;
typedef flatbuffers_uoffset_t *bpio_ConfigurationRequest_mutable_vec_t;
typedef const struct bpio_ConfigurationResponse_table *bpio_ConfigurationResponse_table_t;
typedef struct bpio_ConfigurationResponse_table *bpio_ConfigurationResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_ConfigurationResponse_vec_t;
typedef flatbuffers_uoffset_t *bpio_ConfigurationResponse_mutable_vec_t;
typedef const struct bpio_DataRequest_table *bpio_DataRequest_table_t;
typedef struct bpio_DataRequest_table *bpio_DataRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_DataRequest_vec_t;
typedef flatbuffers_uoffset_t *bpio_DataRequest_mutable_vec_t;
typedef const struct bpio_DataResponse_table *bpio_DataResponse_table_t;
typedef struct bpio_DataResponse_table *bpio_DataResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_DataResponse_vec_t;
typedef flatbuffers_uoffset_t *bpio_DataResponse_mutable_vec_t;
typedef const struct bpio_RequestPacket_table *bpio_RequestPacket_table_t;
typedef struct bpio_RequestPacket_table *bpio_RequestPacket_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_RequestPacket_vec_t;
typedef flatbuffers_uoffset_t *bpio_RequestPacket_mutable_vec_t;
typedef const struct bpio_ResponsePacket_table *bpio_ResponsePacket_table_t;
typedef struct bpio_ResponsePacket_table *bpio_ResponsePacket_mutable_table_t;
typedef const flatbuffers_uoffset_t *bpio_ResponsePacket_vec_t;
typedef flatbuffers_uoffset_t *bpio_ResponsePacket_mutable_vec_t;
#ifndef bpio_StatusRequest_file_identifier
#define bpio_StatusRequest_file_identifier 0
#endif
/* deprecated, use bpio_StatusRequest_file_identifier */
#ifndef bpio_StatusRequest_identifier
#define bpio_StatusRequest_identifier 0
#endif
#define bpio_StatusRequest_type_hash ((flatbuffers_thash_t)0xbe501fa)
#define bpio_StatusRequest_type_identifier "\xfa\x01\xe5\x0b"
#ifndef bpio_StatusRequest_file_extension
#define bpio_StatusRequest_file_extension "bin"
#endif
#ifndef bpio_StatusResponse_file_identifier
#define bpio_StatusResponse_file_identifier 0
#endif
/* deprecated, use bpio_StatusResponse_file_identifier */
#ifndef bpio_StatusResponse_identifier
#define bpio_StatusResponse_identifier 0
#endif
#define bpio_StatusResponse_type_hash ((flatbuffers_thash_t)0xda00c196)
#define bpio_StatusResponse_type_identifier "\x96\xc1\x00\xda"
#ifndef bpio_StatusResponse_file_extension
#define bpio_StatusResponse_file_extension "bin"
#endif
#ifndef bpio_ModeConfiguration_file_identifier
#define bpio_ModeConfiguration_file_identifier 0
#endif
/* deprecated, use bpio_ModeConfiguration_file_identifier */
#ifndef bpio_ModeConfiguration_identifier
#define bpio_ModeConfiguration_identifier 0
#endif
#define bpio_ModeConfiguration_type_hash ((flatbuffers_thash_t)0x14dc505e)
#define bpio_ModeConfiguration_type_identifier "\x5e\x50\xdc\x14"
#ifndef bpio_ModeConfiguration_file_extension
#define bpio_ModeConfiguration_file_extension "bin"
#endif
#ifndef bpio_ConfigurationRequest_file_identifier
#define bpio_ConfigurationRequest_file_identifier 0
#endif
/* deprecated, use bpio_ConfigurationRequest_file_identifier */
#ifndef bpio_ConfigurationRequest_identifier
#define bpio_ConfigurationRequest_identifier 0
#endif
#define bpio_ConfigurationRequest_type_hash ((flatbuffers_thash_t)0x6f10bfec)
#define bpio_ConfigurationRequest_type_identifier "\xec\xbf\x10\x6f"
#ifndef bpio_ConfigurationRequest_file_extension
#define bpio_ConfigurationRequest_file_extension "bin"
#endif
#ifndef bpio_ConfigurationResponse_file_identifier
#define bpio_ConfigurationResponse_file_identifier 0
#endif
/* deprecated, use bpio_ConfigurationResponse_file_identifier */
#ifndef bpio_ConfigurationResponse_identifier
#define bpio_ConfigurationResponse_identifier 0
#endif
#define bpio_ConfigurationResponse_type_hash ((flatbuffers_thash_t)0x27663d80)
#define bpio_ConfigurationResponse_type_identifier "\x80\x3d\x66\x27"
#ifndef bpio_ConfigurationResponse_file_extension
#define bpio_ConfigurationResponse_file_extension "bin"
#endif
#ifndef bpio_DataRequest_file_identifier
#define bpio_DataRequest_file_identifier 0
#endif
/* deprecated, use bpio_DataRequest_file_identifier */
#ifndef bpio_DataRequest_identifier
#define bpio_DataRequest_identifier 0
#endif
#define bpio_DataRequest_type_hash ((flatbuffers_thash_t)0xa5bb54cc)
#define bpio_DataRequest_type_identifier "\xcc\x54\xbb\xa5"
#ifndef bpio_DataRequest_file_extension
#define bpio_DataRequest_file_extension "bin"
#endif
#ifndef bpio_DataResponse_file_identifier
#define bpio_DataResponse_file_identifier 0
#endif
/* deprecated, use bpio_DataResponse_file_identifier */
#ifndef bpio_DataResponse_identifier
#define bpio_DataResponse_identifier 0
#endif
#define bpio_DataResponse_type_hash ((flatbuffers_thash_t)0x586967e0)
#define bpio_DataResponse_type_identifier "\xe0\x67\x69\x58"
#ifndef bpio_DataResponse_file_extension
#define bpio_DataResponse_file_extension "bin"
#endif
#ifndef bpio_RequestPacket_file_identifier
#define bpio_RequestPacket_file_identifier 0
#endif
/* deprecated, use bpio_RequestPacket_file_identifier */
#ifndef bpio_RequestPacket_identifier
#define bpio_RequestPacket_identifier 0
#endif
#define bpio_RequestPacket_type_hash ((flatbuffers_thash_t)0x8efb14ec)
#define bpio_RequestPacket_type_identifier "\xec\x14\xfb\x8e"
#ifndef bpio_RequestPacket_file_extension
#define bpio_RequestPacket_file_extension "bin"
#endif
#ifndef bpio_ResponsePacket_file_identifier
#define bpio_ResponsePacket_file_identifier 0
#endif
/* deprecated, use bpio_ResponsePacket_file_identifier */
#ifndef bpio_ResponsePacket_identifier
#define bpio_ResponsePacket_identifier 0
#endif
#define bpio_ResponsePacket_type_hash ((flatbuffers_thash_t)0x46c40720)
#define bpio_ResponsePacket_type_identifier "\x20\x07\xc4\x46"
#ifndef bpio_ResponsePacket_file_extension
#define bpio_ResponsePacket_file_extension "bin"
#endif

typedef int8_t bpio_StatusRequestTypes_enum_t;
__flatbuffers_define_integer_type(bpio_StatusRequestTypes, bpio_StatusRequestTypes_enum_t, 8)
#define bpio_StatusRequestTypes_All ((bpio_StatusRequestTypes_enum_t)INT8_C(0))
#define bpio_StatusRequestTypes_Version ((bpio_StatusRequestTypes_enum_t)INT8_C(1))
#define bpio_StatusRequestTypes_Mode ((bpio_StatusRequestTypes_enum_t)INT8_C(2))
#define bpio_StatusRequestTypes_Pullup ((bpio_StatusRequestTypes_enum_t)INT8_C(3))
#define bpio_StatusRequestTypes_PSU ((bpio_StatusRequestTypes_enum_t)INT8_C(4))
#define bpio_StatusRequestTypes_ADC ((bpio_StatusRequestTypes_enum_t)INT8_C(5))
#define bpio_StatusRequestTypes_IO ((bpio_StatusRequestTypes_enum_t)INT8_C(6))
#define bpio_StatusRequestTypes_Disk ((bpio_StatusRequestTypes_enum_t)INT8_C(7))
#define bpio_StatusRequestTypes_LED ((bpio_StatusRequestTypes_enum_t)INT8_C(8))

static inline const char *bpio_StatusRequestTypes_name(bpio_StatusRequestTypes_enum_t value)
{
    switch (value) {
    case bpio_StatusRequestTypes_All: return "All";
    case bpio_StatusRequestTypes_Version: return "Version";
    case bpio_StatusRequestTypes_Mode: return "Mode";
    case bpio_StatusRequestTypes_Pullup: return "Pullup";
    case bpio_StatusRequestTypes_PSU: return "PSU";
    case bpio_StatusRequestTypes_ADC: return "ADC";
    case bpio_StatusRequestTypes_IO: return "IO";
    case bpio_StatusRequestTypes_Disk: return "Disk";
    case bpio_StatusRequestTypes_LED: return "LED";
    default: return "";
    }
}

static inline int bpio_StatusRequestTypes_is_known_value(bpio_StatusRequestTypes_enum_t value)
{
    switch (value) {
    case bpio_StatusRequestTypes_All: return 1;
    case bpio_StatusRequestTypes_Version: return 1;
    case bpio_StatusRequestTypes_Mode: return 1;
    case bpio_StatusRequestTypes_Pullup: return 1;
    case bpio_StatusRequestTypes_PSU: return 1;
    case bpio_StatusRequestTypes_ADC: return 1;
    case bpio_StatusRequestTypes_IO: return 1;
    case bpio_StatusRequestTypes_Disk: return 1;
    case bpio_StatusRequestTypes_LED: return 1;
    default: return 0;
    }
}



struct bpio_StatusRequest_table { uint8_t unused__; };

static inline size_t bpio_StatusRequest_vec_len(bpio_StatusRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_StatusRequest_table_t bpio_StatusRequest_vec_at(bpio_StatusRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_StatusRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_StatusRequest)

__flatbuffers_define_vector_field(0, bpio_StatusRequest, query, bpio_StatusRequestTypes_vec_t, 0)

struct bpio_StatusResponse_table { uint8_t unused__; };

static inline size_t bpio_StatusResponse_vec_len(bpio_StatusResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_StatusResponse_table_t bpio_StatusResponse_vec_at(bpio_StatusResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_StatusResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_StatusResponse)

__flatbuffers_define_string_field(0, bpio_StatusResponse, error, 0)
__flatbuffers_define_scalar_field(1, bpio_StatusResponse, version_flatbuffers_major, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(2, bpio_StatusResponse, version_flatbuffers_minor, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(3, bpio_StatusResponse, version_hardware_major, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(4, bpio_StatusResponse, version_hardware_minor, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(5, bpio_StatusResponse, version_firmware_major, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(6, bpio_StatusResponse, version_firmware_minor, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(7, bpio_StatusResponse, version_firmware_git_hash, 0)
__flatbuffers_define_string_field(8, bpio_StatusResponse, version_firmware_date, 0)
__flatbuffers_define_vector_field(9, bpio_StatusResponse, modes_available, flatbuffers_string_vec_t, 0)
__flatbuffers_define_string_field(10, bpio_StatusResponse, mode_current, 0)
__flatbuffers_define_vector_field(11, bpio_StatusResponse, mode_pin_labels, flatbuffers_string_vec_t, 0)
__flatbuffers_define_scalar_field(12, bpio_StatusResponse, mode_bitorder_msb, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(13, bpio_StatusResponse, mode_max_packet_size, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(14, bpio_StatusResponse, mode_max_write, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(15, bpio_StatusResponse, mode_max_read, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(16, bpio_StatusResponse, psu_enabled, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(17, bpio_StatusResponse, psu_set_mv, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(18, bpio_StatusResponse, psu_set_ma, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(19, bpio_StatusResponse, psu_measured_mv, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(20, bpio_StatusResponse, psu_measured_ma, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(21, bpio_StatusResponse, psu_current_error, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(22, bpio_StatusResponse, pullup_enabled, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(23, bpio_StatusResponse, adc_mv, flatbuffers_uint32_vec_t, 0)
__flatbuffers_define_scalar_field(24, bpio_StatusResponse, io_direction, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(25, bpio_StatusResponse, io_value, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(26, bpio_StatusResponse, disk_size_mb, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(27, bpio_StatusResponse, disk_used_mb, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(28, bpio_StatusResponse, led_count, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct bpio_ModeConfiguration_table { uint8_t unused__; };

static inline size_t bpio_ModeConfiguration_vec_len(bpio_ModeConfiguration_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_ModeConfiguration_table_t bpio_ModeConfiguration_vec_at(bpio_ModeConfiguration_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_ModeConfiguration_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_ModeConfiguration)

__flatbuffers_define_scalar_field(0, bpio_ModeConfiguration, speed, flatbuffers_uint32, uint32_t, UINT32_C(20000))
__flatbuffers_define_scalar_field(1, bpio_ModeConfiguration, data_bits, flatbuffers_uint8, uint8_t, UINT8_C(8))
__flatbuffers_define_scalar_field(2, bpio_ModeConfiguration, parity, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(3, bpio_ModeConfiguration, stop_bits, flatbuffers_uint8, uint8_t, UINT8_C(1))
__flatbuffers_define_scalar_field(4, bpio_ModeConfiguration, flow_control, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(5, bpio_ModeConfiguration, signal_inversion, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(6, bpio_ModeConfiguration, clock_stretch, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(7, bpio_ModeConfiguration, clock_polarity, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(8, bpio_ModeConfiguration, clock_phase, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(9, bpio_ModeConfiguration, chip_select_idle, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(1))
__flatbuffers_define_scalar_field(10, bpio_ModeConfiguration, submode, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(11, bpio_ModeConfiguration, tx_modulation, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(12, bpio_ModeConfiguration, rx_sensor, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct bpio_ConfigurationRequest_table { uint8_t unused__; };

static inline size_t bpio_ConfigurationRequest_vec_len(bpio_ConfigurationRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_ConfigurationRequest_table_t bpio_ConfigurationRequest_vec_at(bpio_ConfigurationRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_ConfigurationRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_ConfigurationRequest)

__flatbuffers_define_string_field(0, bpio_ConfigurationRequest, mode, 0)
__flatbuffers_define_table_field(1, bpio_ConfigurationRequest, mode_configuration, bpio_ModeConfiguration_table_t, 0)
__flatbuffers_define_scalar_field(2, bpio_ConfigurationRequest, mode_bitorder_msb, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(3, bpio_ConfigurationRequest, mode_bitorder_lsb, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(4, bpio_ConfigurationRequest, psu_disable, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(5, bpio_ConfigurationRequest, psu_enable, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(6, bpio_ConfigurationRequest, psu_set_mv, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(7, bpio_ConfigurationRequest, psu_set_ma, flatbuffers_uint16, uint16_t, UINT16_C(300))
__flatbuffers_define_scalar_field(8, bpio_ConfigurationRequest, pullup_disable, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(9, bpio_ConfigurationRequest, pullup_enable, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(10, bpio_ConfigurationRequest, io_direction_mask, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(11, bpio_ConfigurationRequest, io_direction, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(12, bpio_ConfigurationRequest, io_value_mask, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(13, bpio_ConfigurationRequest, io_value, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(14, bpio_ConfigurationRequest, led_resume, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(15, bpio_ConfigurationRequest, led_color, flatbuffers_uint32_vec_t, 0)
__flatbuffers_define_string_field(16, bpio_ConfigurationRequest, print_string, 0)
__flatbuffers_define_scalar_field(17, bpio_ConfigurationRequest, hardware_bootloader, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(18, bpio_ConfigurationRequest, hardware_reset, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(19, bpio_ConfigurationRequest, hardware_selftest, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))

struct bpio_ConfigurationResponse_table { uint8_t unused__; };

static inline size_t bpio_ConfigurationResponse_vec_len(bpio_ConfigurationResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_ConfigurationResponse_table_t bpio_ConfigurationResponse_vec_at(bpio_ConfigurationResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_ConfigurationResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_ConfigurationResponse)

__flatbuffers_define_string_field(0, bpio_ConfigurationResponse, error, 0)

struct bpio_DataRequest_table { uint8_t unused__; };

static inline size_t bpio_DataRequest_vec_len(bpio_DataRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_DataRequest_table_t bpio_DataRequest_vec_at(bpio_DataRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_DataRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_DataRequest)

__flatbuffers_define_scalar_field(0, bpio_DataRequest, start_main, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, bpio_DataRequest, start_alt, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(2, bpio_DataRequest, data_write, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_scalar_field(3, bpio_DataRequest, bytes_read, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(4, bpio_DataRequest, stop_main, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(5, bpio_DataRequest, stop_alt, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))

struct bpio_DataResponse_table { uint8_t unused__; };

static inline size_t bpio_DataResponse_vec_len(bpio_DataResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_DataResponse_table_t bpio_DataResponse_vec_at(bpio_DataResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_DataResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_DataResponse)

__flatbuffers_define_string_field(0, bpio_DataResponse, error, 0)
__flatbuffers_define_vector_field(1, bpio_DataResponse, data_read, flatbuffers_uint8_vec_t, 0)
typedef uint8_t bpio_RequestPacketContents_union_type_t;
__flatbuffers_define_integer_type(bpio_RequestPacketContents, bpio_RequestPacketContents_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, bpio_RequestPacketContents)
#define bpio_RequestPacketContents_NONE ((bpio_RequestPacketContents_union_type_t)UINT8_C(0))
#define bpio_RequestPacketContents_StatusRequest ((bpio_RequestPacketContents_union_type_t)UINT8_C(1))
#define bpio_RequestPacketContents_ConfigurationRequest ((bpio_RequestPacketContents_union_type_t)UINT8_C(2))
#define bpio_RequestPacketContents_DataRequest ((bpio_RequestPacketContents_union_type_t)UINT8_C(3))

static inline const char *bpio_RequestPacketContents_type_name(bpio_RequestPacketContents_union_type_t type)
{
    switch (type) {
    case bpio_RequestPacketContents_NONE: return "NONE";
    case bpio_RequestPacketContents_StatusRequest: return "StatusRequest";
    case bpio_RequestPacketContents_ConfigurationRequest: return "ConfigurationRequest";
    case bpio_RequestPacketContents_DataRequest: return "DataRequest";
    default: return "";
    }
}

static inline int bpio_RequestPacketContents_is_known_type(bpio_RequestPacketContents_union_type_t type)
{
    switch (type) {
    case bpio_RequestPacketContents_NONE: return 1;
    case bpio_RequestPacketContents_StatusRequest: return 1;
    case bpio_RequestPacketContents_ConfigurationRequest: return 1;
    case bpio_RequestPacketContents_DataRequest: return 1;
    default: return 0;
    }
}


struct bpio_RequestPacket_table { uint8_t unused__; };

static inline size_t bpio_RequestPacket_vec_len(bpio_RequestPacket_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_RequestPacket_table_t bpio_RequestPacket_vec_at(bpio_RequestPacket_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_RequestPacket_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_RequestPacket)

__flatbuffers_define_scalar_field(0, bpio_RequestPacket, version_major, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, bpio_RequestPacket, minimum_version_minor, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_union_field(flatbuffers_, 3, bpio_RequestPacket, contents, bpio_RequestPacketContents, 0)
typedef uint8_t bpio_ResponsePacketContents_union_type_t;
__flatbuffers_define_integer_type(bpio_ResponsePacketContents, bpio_ResponsePacketContents_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, bpio_ResponsePacketContents)
#define bpio_ResponsePacketContents_NONE ((bpio_ResponsePacketContents_union_type_t)UINT8_C(0))
#define bpio_ResponsePacketContents_StatusResponse ((bpio_ResponsePacketContents_union_type_t)UINT8_C(1))
#define bpio_ResponsePacketContents_ConfigurationResponse ((bpio_ResponsePacketContents_union_type_t)UINT8_C(2))
#define bpio_ResponsePacketContents_DataResponse ((bpio_ResponsePacketContents_union_type_t)UINT8_C(3))

static inline const char *bpio_ResponsePacketContents_type_name(bpio_ResponsePacketContents_union_type_t type)
{
    switch (type) {
    case bpio_ResponsePacketContents_NONE: return "NONE";
    case bpio_ResponsePacketContents_StatusResponse: return "StatusResponse";
    case bpio_ResponsePacketContents_ConfigurationResponse: return "ConfigurationResponse";
    case bpio_ResponsePacketContents_DataResponse: return "DataResponse";
    default: return "";
    }
}

static inline int bpio_ResponsePacketContents_is_known_type(bpio_ResponsePacketContents_union_type_t type)
{
    switch (type) {
    case bpio_ResponsePacketContents_NONE: return 1;
    case bpio_ResponsePacketContents_StatusResponse: return 1;
    case bpio_ResponsePacketContents_ConfigurationResponse: return 1;
    case bpio_ResponsePacketContents_DataResponse: return 1;
    default: return 0;
    }
}


struct bpio_ResponsePacket_table { uint8_t unused__; };

static inline size_t bpio_ResponsePacket_vec_len(bpio_ResponsePacket_vec_t vec)
__flatbuffers_vec_len(vec)
static inline bpio_ResponsePacket_table_t bpio_ResponsePacket_vec_at(bpio_ResponsePacket_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(bpio_ResponsePacket_table_t, vec, i, 0)
__flatbuffers_table_as_root(bpio_ResponsePacket)

__flatbuffers_define_string_field(0, bpio_ResponsePacket, error, 0)
__flatbuffers_define_union_field(flatbuffers_, 2, bpio_ResponsePacket, contents, bpio_ResponsePacketContents, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* BPIO_READER_H */
