#ifndef BPIO_BUILDER_H
#define BPIO_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef BPIO_READER_H
#include "bpio_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __bpio_StatusRequestTypes_formal_args , bpio_StatusRequestTypes_enum_t v0
#define __bpio_StatusRequestTypes_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, bpio_StatusRequestTypes, bpio_StatusRequestTypes_enum_t)

typedef flatbuffers_union_ref_t bpio_RequestPacketContents_union_ref_t;
typedef flatbuffers_union_vec_ref_t bpio_RequestPacketContents_union_vec_ref_t;
static bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_clone(flatbuffers_builder_t *B, bpio_RequestPacketContents_union_t t);
typedef flatbuffers_union_ref_t bpio_ResponsePacketContents_union_ref_t;
typedef flatbuffers_union_vec_ref_t bpio_ResponsePacketContents_union_vec_ref_t;
static bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_clone(flatbuffers_builder_t *B, bpio_ResponsePacketContents_union_t t);

static const flatbuffers_voffset_t __bpio_StatusRequest_required[] = { 0 };
typedef flatbuffers_ref_t bpio_StatusRequest_ref_t;
static bpio_StatusRequest_ref_t bpio_StatusRequest_clone(flatbuffers_builder_t *B, bpio_StatusRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_StatusRequest, 1)

static const flatbuffers_voffset_t __bpio_StatusResponse_required[] = { 0 };
typedef flatbuffers_ref_t bpio_StatusResponse_ref_t;
static bpio_StatusResponse_ref_t bpio_StatusResponse_clone(flatbuffers_builder_t *B, bpio_StatusResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_StatusResponse, 25)

static const flatbuffers_voffset_t __bpio_ModeConfiguration_required[] = { 0 };
typedef flatbuffers_ref_t bpio_ModeConfiguration_ref_t;
static bpio_ModeConfiguration_ref_t bpio_ModeConfiguration_clone(flatbuffers_builder_t *B, bpio_ModeConfiguration_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_ModeConfiguration, 13)

static const flatbuffers_voffset_t __bpio_ConfigurationRequest_required[] = { 0 };
typedef flatbuffers_ref_t bpio_ConfigurationRequest_ref_t;
static bpio_ConfigurationRequest_ref_t bpio_ConfigurationRequest_clone(flatbuffers_builder_t *B, bpio_ConfigurationRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_ConfigurationRequest, 20)

static const flatbuffers_voffset_t __bpio_ConfigurationResponse_required[] = { 0 };
typedef flatbuffers_ref_t bpio_ConfigurationResponse_ref_t;
static bpio_ConfigurationResponse_ref_t bpio_ConfigurationResponse_clone(flatbuffers_builder_t *B, bpio_ConfigurationResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_ConfigurationResponse, 1)

static const flatbuffers_voffset_t __bpio_DataRequest_required[] = { 0 };
typedef flatbuffers_ref_t bpio_DataRequest_ref_t;
static bpio_DataRequest_ref_t bpio_DataRequest_clone(flatbuffers_builder_t *B, bpio_DataRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_DataRequest, 6)

static const flatbuffers_voffset_t __bpio_DataResponse_required[] = { 0 };
typedef flatbuffers_ref_t bpio_DataResponse_ref_t;
static bpio_DataResponse_ref_t bpio_DataResponse_clone(flatbuffers_builder_t *B, bpio_DataResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_DataResponse, 2)

static const flatbuffers_voffset_t __bpio_RequestPacket_required[] = { 0 };
typedef flatbuffers_ref_t bpio_RequestPacket_ref_t;
static bpio_RequestPacket_ref_t bpio_RequestPacket_clone(flatbuffers_builder_t *B, bpio_RequestPacket_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_RequestPacket, 4)

static const flatbuffers_voffset_t __bpio_ErrorResponse_required[] = { 0 };
typedef flatbuffers_ref_t bpio_ErrorResponse_ref_t;
static bpio_ErrorResponse_ref_t bpio_ErrorResponse_clone(flatbuffers_builder_t *B, bpio_ErrorResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_ErrorResponse, 1)

static const flatbuffers_voffset_t __bpio_ResponsePacket_required[] = { 0 };
typedef flatbuffers_ref_t bpio_ResponsePacket_ref_t;
static bpio_ResponsePacket_ref_t bpio_ResponsePacket_clone(flatbuffers_builder_t *B, bpio_ResponsePacket_table_t t);
__flatbuffers_build_table(flatbuffers_, bpio_ResponsePacket, 4)

#define __bpio_StatusRequest_formal_args , bpio_StatusRequestTypes_vec_ref_t v0
#define __bpio_StatusRequest_call_args , v0
static inline bpio_StatusRequest_ref_t bpio_StatusRequest_create(flatbuffers_builder_t *B __bpio_StatusRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_StatusRequest, bpio_StatusRequest_file_identifier, bpio_StatusRequest_type_identifier)

#define __bpio_StatusResponse_formal_args ,\
  flatbuffers_string_ref_t v0, uint8_t v1, uint8_t v2, uint8_t v3,\
  uint8_t v4, flatbuffers_string_ref_t v5, flatbuffers_string_ref_t v6, flatbuffers_string_vec_ref_t v7,\
  flatbuffers_string_ref_t v8, flatbuffers_string_vec_ref_t v9, flatbuffers_bool_t v10, flatbuffers_bool_t v11,\
  uint32_t v12, uint32_t v13, uint32_t v14, uint32_t v15,\
  flatbuffers_bool_t v16, flatbuffers_bool_t v17, uint32_t v18, flatbuffers_uint32_vec_ref_t v19,\
  uint8_t v20, uint8_t v21, float v22, float v23, uint8_t v24
#define __bpio_StatusResponse_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15,\
  v16, v17, v18, v19,\
  v20, v21, v22, v23, v24
static inline bpio_StatusResponse_ref_t bpio_StatusResponse_create(flatbuffers_builder_t *B __bpio_StatusResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_StatusResponse, bpio_StatusResponse_file_identifier, bpio_StatusResponse_type_identifier)

#define __bpio_ModeConfiguration_formal_args ,\
  uint32_t v0, uint8_t v1, flatbuffers_bool_t v2, uint8_t v3,\
  flatbuffers_bool_t v4, flatbuffers_bool_t v5, flatbuffers_bool_t v6, flatbuffers_bool_t v7,\
  flatbuffers_bool_t v8, flatbuffers_bool_t v9, uint8_t v10, uint32_t v11, uint8_t v12
#define __bpio_ModeConfiguration_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11, v12
static inline bpio_ModeConfiguration_ref_t bpio_ModeConfiguration_create(flatbuffers_builder_t *B __bpio_ModeConfiguration_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_ModeConfiguration, bpio_ModeConfiguration_file_identifier, bpio_ModeConfiguration_type_identifier)

#define __bpio_ConfigurationRequest_formal_args ,\
  flatbuffers_string_ref_t v0, bpio_ModeConfiguration_ref_t v1, flatbuffers_bool_t v2, flatbuffers_bool_t v3,\
  flatbuffers_bool_t v4, flatbuffers_bool_t v5, uint32_t v6, uint16_t v7,\
  flatbuffers_bool_t v8, flatbuffers_bool_t v9, uint32_t v10, uint8_t v11,\
  uint8_t v12, uint8_t v13, uint8_t v14, flatbuffers_bool_t v15,\
  flatbuffers_uint32_vec_ref_t v16, flatbuffers_string_ref_t v17, flatbuffers_bool_t v18, flatbuffers_bool_t v19
#define __bpio_ConfigurationRequest_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15,\
  v16, v17, v18, v19
static inline bpio_ConfigurationRequest_ref_t bpio_ConfigurationRequest_create(flatbuffers_builder_t *B __bpio_ConfigurationRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_ConfigurationRequest, bpio_ConfigurationRequest_file_identifier, bpio_ConfigurationRequest_type_identifier)

#define __bpio_ConfigurationResponse_formal_args , flatbuffers_string_ref_t v0
#define __bpio_ConfigurationResponse_call_args , v0
static inline bpio_ConfigurationResponse_ref_t bpio_ConfigurationResponse_create(flatbuffers_builder_t *B __bpio_ConfigurationResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_ConfigurationResponse, bpio_ConfigurationResponse_file_identifier, bpio_ConfigurationResponse_type_identifier)

#define __bpio_DataRequest_formal_args ,\
  flatbuffers_bool_t v0, flatbuffers_bool_t v1, flatbuffers_uint8_vec_ref_t v2, uint16_t v3, flatbuffers_bool_t v4, flatbuffers_bool_t v5
#define __bpio_DataRequest_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline bpio_DataRequest_ref_t bpio_DataRequest_create(flatbuffers_builder_t *B __bpio_DataRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_DataRequest, bpio_DataRequest_file_identifier, bpio_DataRequest_type_identifier)

#define __bpio_DataResponse_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1
#define __bpio_DataResponse_call_args , v0, v1
static inline bpio_DataResponse_ref_t bpio_DataResponse_create(flatbuffers_builder_t *B __bpio_DataResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_DataResponse, bpio_DataResponse_file_identifier, bpio_DataResponse_type_identifier)

#define __bpio_RequestPacket_formal_args , uint8_t v0, uint8_t v1, bpio_RequestPacketContents_union_ref_t v3
#define __bpio_RequestPacket_call_args , v0, v1, v3
static inline bpio_RequestPacket_ref_t bpio_RequestPacket_create(flatbuffers_builder_t *B __bpio_RequestPacket_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_RequestPacket, bpio_RequestPacket_file_identifier, bpio_RequestPacket_type_identifier)

#define __bpio_ErrorResponse_formal_args , flatbuffers_string_ref_t v0
#define __bpio_ErrorResponse_call_args , v0
static inline bpio_ErrorResponse_ref_t bpio_ErrorResponse_create(flatbuffers_builder_t *B __bpio_ErrorResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_ErrorResponse, bpio_ErrorResponse_file_identifier, bpio_ErrorResponse_type_identifier)

#define __bpio_ResponsePacket_formal_args , uint8_t v0, uint8_t v1, bpio_ResponsePacketContents_union_ref_t v3
#define __bpio_ResponsePacket_call_args , v0, v1, v3
static inline bpio_ResponsePacket_ref_t bpio_ResponsePacket_create(flatbuffers_builder_t *B __bpio_ResponsePacket_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, bpio_ResponsePacket, bpio_ResponsePacket_file_identifier, bpio_ResponsePacket_type_identifier)

static inline bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_as_NONE(void)
{ bpio_RequestPacketContents_union_ref_t uref; uref.type = bpio_RequestPacketContents_NONE; uref.value = 0; return uref; }
static inline bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_as_StatusRequest(bpio_StatusRequest_ref_t ref)
{ bpio_RequestPacketContents_union_ref_t uref; uref.type = bpio_RequestPacketContents_StatusRequest; uref.value = ref; return uref; }
static inline bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_as_ConfigurationRequest(bpio_ConfigurationRequest_ref_t ref)
{ bpio_RequestPacketContents_union_ref_t uref; uref.type = bpio_RequestPacketContents_ConfigurationRequest; uref.value = ref; return uref; }
static inline bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_as_DataRequest(bpio_DataRequest_ref_t ref)
{ bpio_RequestPacketContents_union_ref_t uref; uref.type = bpio_RequestPacketContents_DataRequest; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, bpio_RequestPacketContents)

static bpio_RequestPacketContents_union_ref_t bpio_RequestPacketContents_clone(flatbuffers_builder_t *B, bpio_RequestPacketContents_union_t u)
{
    switch (u.type) {
    case 1: return bpio_RequestPacketContents_as_StatusRequest(bpio_StatusRequest_clone(B, (bpio_StatusRequest_table_t)u.value));
    case 2: return bpio_RequestPacketContents_as_ConfigurationRequest(bpio_ConfigurationRequest_clone(B, (bpio_ConfigurationRequest_table_t)u.value));
    case 3: return bpio_RequestPacketContents_as_DataRequest(bpio_DataRequest_clone(B, (bpio_DataRequest_table_t)u.value));
    default: return bpio_RequestPacketContents_as_NONE();
    }
}

static inline bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_as_NONE(void)
{ bpio_ResponsePacketContents_union_ref_t uref; uref.type = bpio_ResponsePacketContents_NONE; uref.value = 0; return uref; }
static inline bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_as_ErrorResponse(bpio_ErrorResponse_ref_t ref)
{ bpio_ResponsePacketContents_union_ref_t uref; uref.type = bpio_ResponsePacketContents_ErrorResponse; uref.value = ref; return uref; }
static inline bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_as_StatusResponse(bpio_StatusResponse_ref_t ref)
{ bpio_ResponsePacketContents_union_ref_t uref; uref.type = bpio_ResponsePacketContents_StatusResponse; uref.value = ref; return uref; }
static inline bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_as_ConfigurationResponse(bpio_ConfigurationResponse_ref_t ref)
{ bpio_ResponsePacketContents_union_ref_t uref; uref.type = bpio_ResponsePacketContents_ConfigurationResponse; uref.value = ref; return uref; }
static inline bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_as_DataResponse(bpio_DataResponse_ref_t ref)
{ bpio_ResponsePacketContents_union_ref_t uref; uref.type = bpio_ResponsePacketContents_DataResponse; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, bpio_ResponsePacketContents)

static bpio_ResponsePacketContents_union_ref_t bpio_ResponsePacketContents_clone(flatbuffers_builder_t *B, bpio_ResponsePacketContents_union_t u)
{
    switch (u.type) {
    case 1: return bpio_ResponsePacketContents_as_ErrorResponse(bpio_ErrorResponse_clone(B, (bpio_ErrorResponse_table_t)u.value));
    case 2: return bpio_ResponsePacketContents_as_StatusResponse(bpio_StatusResponse_clone(B, (bpio_StatusResponse_table_t)u.value));
    case 3: return bpio_ResponsePacketContents_as_ConfigurationResponse(bpio_ConfigurationResponse_clone(B, (bpio_ConfigurationResponse_table_t)u.value));
    case 4: return bpio_ResponsePacketContents_as_DataResponse(bpio_DataResponse_clone(B, (bpio_DataResponse_table_t)u.value));
    default: return bpio_ResponsePacketContents_as_NONE();
    }
}

__flatbuffers_build_vector_field(0, flatbuffers_, bpio_StatusRequest_query, bpio_StatusRequestTypes, bpio_StatusRequestTypes_enum_t, bpio_StatusRequest)

static inline bpio_StatusRequest_ref_t bpio_StatusRequest_create(flatbuffers_builder_t *B __bpio_StatusRequest_formal_args)
{
    if (bpio_StatusRequest_start(B)
        || bpio_StatusRequest_query_add(B, v0)) {
        return 0;
    }
    return bpio_StatusRequest_end(B);
}

static bpio_StatusRequest_ref_t bpio_StatusRequest_clone(flatbuffers_builder_t *B, bpio_StatusRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_StatusRequest_start(B)
        || bpio_StatusRequest_query_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_StatusRequest_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, bpio_StatusResponse_error, bpio_StatusResponse)
__flatbuffers_build_scalar_field(1, flatbuffers_, bpio_StatusResponse_hardware_version_major, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(2, flatbuffers_, bpio_StatusResponse_hardware_version_minor, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(3, flatbuffers_, bpio_StatusResponse_firmware_version_major, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(4, flatbuffers_, bpio_StatusResponse_firmware_version_minor, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_string_field(5, flatbuffers_, bpio_StatusResponse_firmware_git_hash, bpio_StatusResponse)
__flatbuffers_build_string_field(6, flatbuffers_, bpio_StatusResponse_firmware_date, bpio_StatusResponse)
__flatbuffers_build_string_vector_field(7, flatbuffers_, bpio_StatusResponse_modes_available, bpio_StatusResponse)
__flatbuffers_build_string_field(8, flatbuffers_, bpio_StatusResponse_mode_current, bpio_StatusResponse)
__flatbuffers_build_string_vector_field(9, flatbuffers_, bpio_StatusResponse_mode_pin_labels, bpio_StatusResponse)
__flatbuffers_build_scalar_field(10, flatbuffers_, bpio_StatusResponse_mode_bitorder_msb, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(11, flatbuffers_, bpio_StatusResponse_psu_enabled, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(12, flatbuffers_, bpio_StatusResponse_psu_set_mv, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(13, flatbuffers_, bpio_StatusResponse_psu_set_ma, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(14, flatbuffers_, bpio_StatusResponse_psu_measured_mv, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(15, flatbuffers_, bpio_StatusResponse_psu_measured_ma, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(16, flatbuffers_, bpio_StatusResponse_psu_current_error, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(17, flatbuffers_, bpio_StatusResponse_pullup_enabled, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(18, flatbuffers_, bpio_StatusResponse_pullx_config, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_StatusResponse)
__flatbuffers_build_vector_field(19, flatbuffers_, bpio_StatusResponse_adc_mv, flatbuffers_uint32, uint32_t, bpio_StatusResponse)
__flatbuffers_build_scalar_field(20, flatbuffers_, bpio_StatusResponse_io_direction, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(21, flatbuffers_, bpio_StatusResponse_io_value, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)
__flatbuffers_build_scalar_field(22, flatbuffers_, bpio_StatusResponse_disk_size_mb, flatbuffers_float, float, 4, 4, 0.00000000f, bpio_StatusResponse)
__flatbuffers_build_scalar_field(23, flatbuffers_, bpio_StatusResponse_disk_used_mb, flatbuffers_float, float, 4, 4, 0.00000000f, bpio_StatusResponse)
__flatbuffers_build_scalar_field(24, flatbuffers_, bpio_StatusResponse_led_count, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_StatusResponse)

static inline bpio_StatusResponse_ref_t bpio_StatusResponse_create(flatbuffers_builder_t *B __bpio_StatusResponse_formal_args)
{
    if (bpio_StatusResponse_start(B)
        || bpio_StatusResponse_error_add(B, v0)
        || bpio_StatusResponse_firmware_git_hash_add(B, v5)
        || bpio_StatusResponse_firmware_date_add(B, v6)
        || bpio_StatusResponse_modes_available_add(B, v7)
        || bpio_StatusResponse_mode_current_add(B, v8)
        || bpio_StatusResponse_mode_pin_labels_add(B, v9)
        || bpio_StatusResponse_psu_set_mv_add(B, v12)
        || bpio_StatusResponse_psu_set_ma_add(B, v13)
        || bpio_StatusResponse_psu_measured_mv_add(B, v14)
        || bpio_StatusResponse_psu_measured_ma_add(B, v15)
        || bpio_StatusResponse_pullx_config_add(B, v18)
        || bpio_StatusResponse_adc_mv_add(B, v19)
        || bpio_StatusResponse_disk_size_mb_add(B, v22)
        || bpio_StatusResponse_disk_used_mb_add(B, v23)
        || bpio_StatusResponse_hardware_version_major_add(B, v1)
        || bpio_StatusResponse_hardware_version_minor_add(B, v2)
        || bpio_StatusResponse_firmware_version_major_add(B, v3)
        || bpio_StatusResponse_firmware_version_minor_add(B, v4)
        || bpio_StatusResponse_mode_bitorder_msb_add(B, v10)
        || bpio_StatusResponse_psu_enabled_add(B, v11)
        || bpio_StatusResponse_psu_current_error_add(B, v16)
        || bpio_StatusResponse_pullup_enabled_add(B, v17)
        || bpio_StatusResponse_io_direction_add(B, v20)
        || bpio_StatusResponse_io_value_add(B, v21)
        || bpio_StatusResponse_led_count_add(B, v24)) {
        return 0;
    }
    return bpio_StatusResponse_end(B);
}

static bpio_StatusResponse_ref_t bpio_StatusResponse_clone(flatbuffers_builder_t *B, bpio_StatusResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_StatusResponse_start(B)
        || bpio_StatusResponse_error_pick(B, t)
        || bpio_StatusResponse_firmware_git_hash_pick(B, t)
        || bpio_StatusResponse_firmware_date_pick(B, t)
        || bpio_StatusResponse_modes_available_pick(B, t)
        || bpio_StatusResponse_mode_current_pick(B, t)
        || bpio_StatusResponse_mode_pin_labels_pick(B, t)
        || bpio_StatusResponse_psu_set_mv_pick(B, t)
        || bpio_StatusResponse_psu_set_ma_pick(B, t)
        || bpio_StatusResponse_psu_measured_mv_pick(B, t)
        || bpio_StatusResponse_psu_measured_ma_pick(B, t)
        || bpio_StatusResponse_pullx_config_pick(B, t)
        || bpio_StatusResponse_adc_mv_pick(B, t)
        || bpio_StatusResponse_disk_size_mb_pick(B, t)
        || bpio_StatusResponse_disk_used_mb_pick(B, t)
        || bpio_StatusResponse_hardware_version_major_pick(B, t)
        || bpio_StatusResponse_hardware_version_minor_pick(B, t)
        || bpio_StatusResponse_firmware_version_major_pick(B, t)
        || bpio_StatusResponse_firmware_version_minor_pick(B, t)
        || bpio_StatusResponse_mode_bitorder_msb_pick(B, t)
        || bpio_StatusResponse_psu_enabled_pick(B, t)
        || bpio_StatusResponse_psu_current_error_pick(B, t)
        || bpio_StatusResponse_pullup_enabled_pick(B, t)
        || bpio_StatusResponse_io_direction_pick(B, t)
        || bpio_StatusResponse_io_value_pick(B, t)
        || bpio_StatusResponse_led_count_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_StatusResponse_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, bpio_ModeConfiguration_speed, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(20000), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(1, flatbuffers_, bpio_ModeConfiguration_data_bits, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(8), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(2, flatbuffers_, bpio_ModeConfiguration_parity, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(3, flatbuffers_, bpio_ModeConfiguration_stop_bits, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(1), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(4, flatbuffers_, bpio_ModeConfiguration_flow_control, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(5, flatbuffers_, bpio_ModeConfiguration_signal_inversion, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(6, flatbuffers_, bpio_ModeConfiguration_clock_stretch, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(7, flatbuffers_, bpio_ModeConfiguration_clock_polarity, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(8, flatbuffers_, bpio_ModeConfiguration_clock_phase, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(9, flatbuffers_, bpio_ModeConfiguration_chip_select_idle, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(1), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(10, flatbuffers_, bpio_ModeConfiguration_submode, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(11, flatbuffers_, bpio_ModeConfiguration_tx_modulation, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_ModeConfiguration)
__flatbuffers_build_scalar_field(12, flatbuffers_, bpio_ModeConfiguration_rx_sensor, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ModeConfiguration)

static inline bpio_ModeConfiguration_ref_t bpio_ModeConfiguration_create(flatbuffers_builder_t *B __bpio_ModeConfiguration_formal_args)
{
    if (bpio_ModeConfiguration_start(B)
        || bpio_ModeConfiguration_speed_add(B, v0)
        || bpio_ModeConfiguration_tx_modulation_add(B, v11)
        || bpio_ModeConfiguration_data_bits_add(B, v1)
        || bpio_ModeConfiguration_parity_add(B, v2)
        || bpio_ModeConfiguration_stop_bits_add(B, v3)
        || bpio_ModeConfiguration_flow_control_add(B, v4)
        || bpio_ModeConfiguration_signal_inversion_add(B, v5)
        || bpio_ModeConfiguration_clock_stretch_add(B, v6)
        || bpio_ModeConfiguration_clock_polarity_add(B, v7)
        || bpio_ModeConfiguration_clock_phase_add(B, v8)
        || bpio_ModeConfiguration_chip_select_idle_add(B, v9)
        || bpio_ModeConfiguration_submode_add(B, v10)
        || bpio_ModeConfiguration_rx_sensor_add(B, v12)) {
        return 0;
    }
    return bpio_ModeConfiguration_end(B);
}

static bpio_ModeConfiguration_ref_t bpio_ModeConfiguration_clone(flatbuffers_builder_t *B, bpio_ModeConfiguration_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_ModeConfiguration_start(B)
        || bpio_ModeConfiguration_speed_pick(B, t)
        || bpio_ModeConfiguration_tx_modulation_pick(B, t)
        || bpio_ModeConfiguration_data_bits_pick(B, t)
        || bpio_ModeConfiguration_parity_pick(B, t)
        || bpio_ModeConfiguration_stop_bits_pick(B, t)
        || bpio_ModeConfiguration_flow_control_pick(B, t)
        || bpio_ModeConfiguration_signal_inversion_pick(B, t)
        || bpio_ModeConfiguration_clock_stretch_pick(B, t)
        || bpio_ModeConfiguration_clock_polarity_pick(B, t)
        || bpio_ModeConfiguration_clock_phase_pick(B, t)
        || bpio_ModeConfiguration_chip_select_idle_pick(B, t)
        || bpio_ModeConfiguration_submode_pick(B, t)
        || bpio_ModeConfiguration_rx_sensor_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_ModeConfiguration_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, bpio_ConfigurationRequest_mode, bpio_ConfigurationRequest)
__flatbuffers_build_table_field(1, flatbuffers_, bpio_ConfigurationRequest_mode_configuration, bpio_ModeConfiguration, bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(2, flatbuffers_, bpio_ConfigurationRequest_mode_bitorder_msb, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(3, flatbuffers_, bpio_ConfigurationRequest_mode_bitorder_lsb, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(4, flatbuffers_, bpio_ConfigurationRequest_psu_disable, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(5, flatbuffers_, bpio_ConfigurationRequest_psu_enable, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(6, flatbuffers_, bpio_ConfigurationRequest_psu_set_mv, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(7, flatbuffers_, bpio_ConfigurationRequest_psu_set_ma, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(300), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(8, flatbuffers_, bpio_ConfigurationRequest_pullup_disable, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(9, flatbuffers_, bpio_ConfigurationRequest_pullup_enable, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(10, flatbuffers_, bpio_ConfigurationRequest_pullx_config, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(11, flatbuffers_, bpio_ConfigurationRequest_io_direction_mask, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(12, flatbuffers_, bpio_ConfigurationRequest_io_direction, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(13, flatbuffers_, bpio_ConfigurationRequest_io_value_mask, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(14, flatbuffers_, bpio_ConfigurationRequest_io_value, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(15, flatbuffers_, bpio_ConfigurationRequest_led_resume, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_vector_field(16, flatbuffers_, bpio_ConfigurationRequest_led_color, flatbuffers_uint32, uint32_t, bpio_ConfigurationRequest)
__flatbuffers_build_string_field(17, flatbuffers_, bpio_ConfigurationRequest_print_string, bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(18, flatbuffers_, bpio_ConfigurationRequest_hardware_bootloader, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)
__flatbuffers_build_scalar_field(19, flatbuffers_, bpio_ConfigurationRequest_hardware_reset, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_ConfigurationRequest)

static inline bpio_ConfigurationRequest_ref_t bpio_ConfigurationRequest_create(flatbuffers_builder_t *B __bpio_ConfigurationRequest_formal_args)
{
    if (bpio_ConfigurationRequest_start(B)
        || bpio_ConfigurationRequest_mode_add(B, v0)
        || bpio_ConfigurationRequest_mode_configuration_add(B, v1)
        || bpio_ConfigurationRequest_psu_set_mv_add(B, v6)
        || bpio_ConfigurationRequest_pullx_config_add(B, v10)
        || bpio_ConfigurationRequest_led_color_add(B, v16)
        || bpio_ConfigurationRequest_print_string_add(B, v17)
        || bpio_ConfigurationRequest_psu_set_ma_add(B, v7)
        || bpio_ConfigurationRequest_mode_bitorder_msb_add(B, v2)
        || bpio_ConfigurationRequest_mode_bitorder_lsb_add(B, v3)
        || bpio_ConfigurationRequest_psu_disable_add(B, v4)
        || bpio_ConfigurationRequest_psu_enable_add(B, v5)
        || bpio_ConfigurationRequest_pullup_disable_add(B, v8)
        || bpio_ConfigurationRequest_pullup_enable_add(B, v9)
        || bpio_ConfigurationRequest_io_direction_mask_add(B, v11)
        || bpio_ConfigurationRequest_io_direction_add(B, v12)
        || bpio_ConfigurationRequest_io_value_mask_add(B, v13)
        || bpio_ConfigurationRequest_io_value_add(B, v14)
        || bpio_ConfigurationRequest_led_resume_add(B, v15)
        || bpio_ConfigurationRequest_hardware_bootloader_add(B, v18)
        || bpio_ConfigurationRequest_hardware_reset_add(B, v19)) {
        return 0;
    }
    return bpio_ConfigurationRequest_end(B);
}

static bpio_ConfigurationRequest_ref_t bpio_ConfigurationRequest_clone(flatbuffers_builder_t *B, bpio_ConfigurationRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_ConfigurationRequest_start(B)
        || bpio_ConfigurationRequest_mode_pick(B, t)
        || bpio_ConfigurationRequest_mode_configuration_pick(B, t)
        || bpio_ConfigurationRequest_psu_set_mv_pick(B, t)
        || bpio_ConfigurationRequest_pullx_config_pick(B, t)
        || bpio_ConfigurationRequest_led_color_pick(B, t)
        || bpio_ConfigurationRequest_print_string_pick(B, t)
        || bpio_ConfigurationRequest_psu_set_ma_pick(B, t)
        || bpio_ConfigurationRequest_mode_bitorder_msb_pick(B, t)
        || bpio_ConfigurationRequest_mode_bitorder_lsb_pick(B, t)
        || bpio_ConfigurationRequest_psu_disable_pick(B, t)
        || bpio_ConfigurationRequest_psu_enable_pick(B, t)
        || bpio_ConfigurationRequest_pullup_disable_pick(B, t)
        || bpio_ConfigurationRequest_pullup_enable_pick(B, t)
        || bpio_ConfigurationRequest_io_direction_mask_pick(B, t)
        || bpio_ConfigurationRequest_io_direction_pick(B, t)
        || bpio_ConfigurationRequest_io_value_mask_pick(B, t)
        || bpio_ConfigurationRequest_io_value_pick(B, t)
        || bpio_ConfigurationRequest_led_resume_pick(B, t)
        || bpio_ConfigurationRequest_hardware_bootloader_pick(B, t)
        || bpio_ConfigurationRequest_hardware_reset_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_ConfigurationRequest_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, bpio_ConfigurationResponse_error, bpio_ConfigurationResponse)

static inline bpio_ConfigurationResponse_ref_t bpio_ConfigurationResponse_create(flatbuffers_builder_t *B __bpio_ConfigurationResponse_formal_args)
{
    if (bpio_ConfigurationResponse_start(B)
        || bpio_ConfigurationResponse_error_add(B, v0)) {
        return 0;
    }
    return bpio_ConfigurationResponse_end(B);
}

static bpio_ConfigurationResponse_ref_t bpio_ConfigurationResponse_clone(flatbuffers_builder_t *B, bpio_ConfigurationResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_ConfigurationResponse_start(B)
        || bpio_ConfigurationResponse_error_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_ConfigurationResponse_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, bpio_DataRequest_start_main, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_DataRequest)
__flatbuffers_build_scalar_field(1, flatbuffers_, bpio_DataRequest_start_alt, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_DataRequest)
__flatbuffers_build_vector_field(2, flatbuffers_, bpio_DataRequest_data_write, flatbuffers_uint8, uint8_t, bpio_DataRequest)
__flatbuffers_build_scalar_field(3, flatbuffers_, bpio_DataRequest_bytes_read, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), bpio_DataRequest)
__flatbuffers_build_scalar_field(4, flatbuffers_, bpio_DataRequest_stop_main, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_DataRequest)
__flatbuffers_build_scalar_field(5, flatbuffers_, bpio_DataRequest_stop_alt, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), bpio_DataRequest)

static inline bpio_DataRequest_ref_t bpio_DataRequest_create(flatbuffers_builder_t *B __bpio_DataRequest_formal_args)
{
    if (bpio_DataRequest_start(B)
        || bpio_DataRequest_data_write_add(B, v2)
        || bpio_DataRequest_bytes_read_add(B, v3)
        || bpio_DataRequest_start_main_add(B, v0)
        || bpio_DataRequest_start_alt_add(B, v1)
        || bpio_DataRequest_stop_main_add(B, v4)
        || bpio_DataRequest_stop_alt_add(B, v5)) {
        return 0;
    }
    return bpio_DataRequest_end(B);
}

static bpio_DataRequest_ref_t bpio_DataRequest_clone(flatbuffers_builder_t *B, bpio_DataRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_DataRequest_start(B)
        || bpio_DataRequest_data_write_pick(B, t)
        || bpio_DataRequest_bytes_read_pick(B, t)
        || bpio_DataRequest_start_main_pick(B, t)
        || bpio_DataRequest_start_alt_pick(B, t)
        || bpio_DataRequest_stop_main_pick(B, t)
        || bpio_DataRequest_stop_alt_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_DataRequest_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, bpio_DataResponse_error, bpio_DataResponse)
__flatbuffers_build_vector_field(1, flatbuffers_, bpio_DataResponse_data_read, flatbuffers_uint8, uint8_t, bpio_DataResponse)

static inline bpio_DataResponse_ref_t bpio_DataResponse_create(flatbuffers_builder_t *B __bpio_DataResponse_formal_args)
{
    if (bpio_DataResponse_start(B)
        || bpio_DataResponse_error_add(B, v0)
        || bpio_DataResponse_data_read_add(B, v1)) {
        return 0;
    }
    return bpio_DataResponse_end(B);
}

static bpio_DataResponse_ref_t bpio_DataResponse_clone(flatbuffers_builder_t *B, bpio_DataResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_DataResponse_start(B)
        || bpio_DataResponse_error_pick(B, t)
        || bpio_DataResponse_data_read_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_DataResponse_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, bpio_RequestPacket_version_major, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_RequestPacket)
__flatbuffers_build_scalar_field(1, flatbuffers_, bpio_RequestPacket_version_minor, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(1), bpio_RequestPacket)
__flatbuffers_build_union_field(3, flatbuffers_, bpio_RequestPacket_contents, bpio_RequestPacketContents, bpio_RequestPacket)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_RequestPacket_contents, bpio_RequestPacketContents, StatusRequest, bpio_StatusRequest)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_RequestPacket_contents, bpio_RequestPacketContents, ConfigurationRequest, bpio_ConfigurationRequest)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_RequestPacket_contents, bpio_RequestPacketContents, DataRequest, bpio_DataRequest)

static inline bpio_RequestPacket_ref_t bpio_RequestPacket_create(flatbuffers_builder_t *B __bpio_RequestPacket_formal_args)
{
    if (bpio_RequestPacket_start(B)
        || bpio_RequestPacket_contents_add_value(B, v3)
        || bpio_RequestPacket_version_major_add(B, v0)
        || bpio_RequestPacket_version_minor_add(B, v1)
        || bpio_RequestPacket_contents_add_type(B, v3.type)) {
        return 0;
    }
    return bpio_RequestPacket_end(B);
}

static bpio_RequestPacket_ref_t bpio_RequestPacket_clone(flatbuffers_builder_t *B, bpio_RequestPacket_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_RequestPacket_start(B)
        || bpio_RequestPacket_contents_pick(B, t)
        || bpio_RequestPacket_version_major_pick(B, t)
        || bpio_RequestPacket_version_minor_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_RequestPacket_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, bpio_ErrorResponse_error, bpio_ErrorResponse)

static inline bpio_ErrorResponse_ref_t bpio_ErrorResponse_create(flatbuffers_builder_t *B __bpio_ErrorResponse_formal_args)
{
    if (bpio_ErrorResponse_start(B)
        || bpio_ErrorResponse_error_add(B, v0)) {
        return 0;
    }
    return bpio_ErrorResponse_end(B);
}

static bpio_ErrorResponse_ref_t bpio_ErrorResponse_clone(flatbuffers_builder_t *B, bpio_ErrorResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_ErrorResponse_start(B)
        || bpio_ErrorResponse_error_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_ErrorResponse_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, bpio_ResponsePacket_version_major, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), bpio_ResponsePacket)
__flatbuffers_build_scalar_field(1, flatbuffers_, bpio_ResponsePacket_version_minor, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(1), bpio_ResponsePacket)
__flatbuffers_build_union_field(3, flatbuffers_, bpio_ResponsePacket_contents, bpio_ResponsePacketContents, bpio_ResponsePacket)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_ResponsePacket_contents, bpio_ResponsePacketContents, ErrorResponse, bpio_ErrorResponse)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_ResponsePacket_contents, bpio_ResponsePacketContents, StatusResponse, bpio_StatusResponse)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_ResponsePacket_contents, bpio_ResponsePacketContents, ConfigurationResponse, bpio_ConfigurationResponse)
__flatbuffers_build_union_table_value_field(flatbuffers_, bpio_ResponsePacket_contents, bpio_ResponsePacketContents, DataResponse, bpio_DataResponse)

static inline bpio_ResponsePacket_ref_t bpio_ResponsePacket_create(flatbuffers_builder_t *B __bpio_ResponsePacket_formal_args)
{
    if (bpio_ResponsePacket_start(B)
        || bpio_ResponsePacket_contents_add_value(B, v3)
        || bpio_ResponsePacket_version_major_add(B, v0)
        || bpio_ResponsePacket_version_minor_add(B, v1)
        || bpio_ResponsePacket_contents_add_type(B, v3.type)) {
        return 0;
    }
    return bpio_ResponsePacket_end(B);
}

static bpio_ResponsePacket_ref_t bpio_ResponsePacket_clone(flatbuffers_builder_t *B, bpio_ResponsePacket_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (bpio_ResponsePacket_start(B)
        || bpio_ResponsePacket_contents_pick(B, t)
        || bpio_ResponsePacket_version_major_pick(B, t)
        || bpio_ResponsePacket_version_minor_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, bpio_ResponsePacket_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* BPIO_BUILDER_H */
