#ifndef BPIO_READER_H
#define BPIO_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct I2C_Example_I2CRWRequest_table *I2C_Example_I2CRWRequest_table_t;
typedef struct I2C_Example_I2CRWRequest_table *I2C_Example_I2CRWRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *I2C_Example_I2CRWRequest_vec_t;
typedef flatbuffers_uoffset_t *I2C_Example_I2CRWRequest_mutable_vec_t;
typedef const struct I2C_Example_I2CRWResponse_table *I2C_Example_I2CRWResponse_table_t;
typedef struct I2C_Example_I2CRWResponse_table *I2C_Example_I2CRWResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *I2C_Example_I2CRWResponse_vec_t;
typedef flatbuffers_uoffset_t *I2C_Example_I2CRWResponse_mutable_vec_t;
#ifndef I2C_Example_I2CRWRequest_file_identifier
#define I2C_Example_I2CRWRequest_file_identifier 0
#endif
/* deprecated, use I2C_Example_I2CRWRequest_file_identifier */
#ifndef I2C_Example_I2CRWRequest_identifier
#define I2C_Example_I2CRWRequest_identifier 0
#endif
#define I2C_Example_I2CRWRequest_type_hash ((flatbuffers_thash_t)0xcdca63db)
#define I2C_Example_I2CRWRequest_type_identifier "\xdb\x63\xca\xcd"
#ifndef I2C_Example_I2CRWRequest_file_extension
#define I2C_Example_I2CRWRequest_file_extension "bin"
#endif
#ifndef I2C_Example_I2CRWResponse_file_identifier
#define I2C_Example_I2CRWResponse_file_identifier 0
#endif
/* deprecated, use I2C_Example_I2CRWResponse_file_identifier */
#ifndef I2C_Example_I2CRWResponse_identifier
#define I2C_Example_I2CRWResponse_identifier 0
#endif
#define I2C_Example_I2CRWResponse_type_hash ((flatbuffers_thash_t)0xdf4d36d9)
#define I2C_Example_I2CRWResponse_type_identifier "\xd9\x36\x4d\xdf"
#ifndef I2C_Example_I2CRWResponse_file_extension
#define I2C_Example_I2CRWResponse_file_extension "bin"
#endif



struct I2C_Example_I2CRWRequest_table { uint8_t unused__; };

static inline size_t I2C_Example_I2CRWRequest_vec_len(I2C_Example_I2CRWRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline I2C_Example_I2CRWRequest_table_t I2C_Example_I2CRWRequest_vec_at(I2C_Example_I2CRWRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(I2C_Example_I2CRWRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(I2C_Example_I2CRWRequest)

__flatbuffers_define_scalar_field(0, I2C_Example_I2CRWRequest, i2cstart, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(1))
__flatbuffers_define_scalar_field(1, I2C_Example_I2CRWRequest, i2caddr, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_vector_field(2, I2C_Example_I2CRWRequest, i2cdata, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_scalar_field(3, I2C_Example_I2CRWRequest, i2creadbytes, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(4, I2C_Example_I2CRWRequest, i2cstop, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(1))

struct I2C_Example_I2CRWResponse_table { uint8_t unused__; };

static inline size_t I2C_Example_I2CRWResponse_vec_len(I2C_Example_I2CRWResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline I2C_Example_I2CRWResponse_table_t I2C_Example_I2CRWResponse_vec_at(I2C_Example_I2CRWResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(I2C_Example_I2CRWResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(I2C_Example_I2CRWResponse)

__flatbuffers_define_scalar_field(0, I2C_Example_I2CRWResponse, i2cack, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(1, I2C_Example_I2CRWResponse, i2cdata, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_string_field(2, I2C_Example_I2CRWResponse, i2cerror_message, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* BPIO_READER_H */
