/**
 * @file syntax.h
 * @brief Command syntax compiler, executor, and post-processor
 * 
 * This file declares the three-phase syntax processing system:
 * 1. Compilation: Parse user command string into bytecode
 * 2. Execution: Run bytecode to perform protocol operations
 * 3. Post-processing: Format and display results to user
 * 
 * @author Bus Pirate Project
 * @date 2024-2026
 */

#ifndef SYNTAX_H
#define SYNTAX_H

#include "bytecode.h"

/**
 * @brief Compile user command string into bytecode
 * 
 * Parses the command line syntax and generates bytecode instructions
 * for protocol operations. Supports:
 * - Numbers in various formats (binary, hex, decimal)
 * - String literals
 * - Protocol operations (start, stop, read, write)
 * - Pin operations (aux, ADC)
 * - Delays and clock manipulation
 * 
 * @return SSTATUS_OK if compilation successful
 * @return SSTATUS_ERROR if syntax error encountered
 * 
 * @note Maximum 1024 bytecode instructions (SYN_MAX_LENGTH)
 * @note Performs bounds checking and pin conflict detection
 */
SYNTAX_STATUS syntax_compile(void);

/**
 * @brief Execute compiled bytecode
 * 
 * Runs the bytecode generated by syntax_compile(), invoking the
 * appropriate protocol operations and storing results.
 * 
 * @return SSTATUS_OK if execution successful (even with errors in results)
 * @return SSTATUS_ERROR if fatal error occurred
 * 
 * @note Execution stops on first error but allows post-processing to display it
 */
SYNTAX_STATUS syntax_run(void);

/**
 * @brief Post-process and display execution results
 * 
 * Formats and displays the results from syntax_run() to the user,
 * including data values, error messages, and protocol-specific output.
 * 
 * @return SSTATUS_OK if post-processing successful
 * @return SSTATUS_ERROR if error occurred during formatting
 */
SYNTAX_STATUS syntax_post(void);

#endif // SYNTAX_H
