
#include <stdio.h>
#include <stdint.h>
#include "../universalprogrammer_pinout.h"

int main(void)
{
  int i;
  uint32_t temp;
  
  printf("// generated by makelut_62xx.c\r\n");
  printf("// (C)hris van Dongen 2025-26\r\n\r\n");

  printf("const uint32_t lut_62xx_lo[] ={");

  for(i=0; i<256; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_62XX_A0;
    if(i&0x02) temp|=UP_62XX_A1;
    if(i&0x04) temp|=UP_62XX_A2;
    if(i&0x08) temp|=UP_62XX_A3;
    if(i&0x10) temp|=UP_62XX_A4;
    if(i&0x20) temp|=UP_62XX_A5;
    if(i&0x40) temp|=UP_62XX_A6;
    if(i&0x80) temp|=UP_62XX_A7;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  printf("const uint32_t lut_62xx_mi[] ={");

  for(i=0; i<256; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_62XX_A8;
    if(i&0x02) temp|=UP_62XX_A9;
    if(i&0x04) temp|=UP_62XX_A10;
    if(i&0x08) temp|=UP_62XX_A11;
    if(i&0x10) temp|=UP_62XX_A12;
    if(i&0x20) temp|=UP_62XX_A13;
    if(i&0x40) temp|=UP_62XX_A14;
    if(i&0x80) temp|=UP_62XX_A15;

    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  printf("const uint32_t lut_62xx_hi[] ={");

  for(i=0; i<2; i++)
  {
    if((i&0x07)==0) printf("\r\n");
    temp=0;
    
    if(i&0x01) temp|=UP_27XX_A16;
    
    printf(" 0x%08X,", temp);
  }
  printf("\r\n};\r\n\r\n");
  
  return 0;
}
